Repository uxlfoundation/oneDAL, pull requests merged in 2020-10, with the labels that each got.

#1020 fix kmeans_init pre- and post- conditions
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
Labels: backport-2021, dpc++

#1019 fix kmeans pre- and post- conditions
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
Labels: backport-2021, dpc++

#1033 oneAPI error handling update
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_brute_force.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_brute_force.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_kd_tree_dpc.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_kd_tree_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_smo_dpc.cpp
  cpp/oneapi/dal/backend/interop/error_converter.cpp
  cpp/oneapi/dal/exceptions.cpp
  cpp/oneapi/dal/exceptions.hpp
  examples/oneapi/dpc/source/decision_forest/df_cls_dense_batch.cpp
  examples/oneapi/dpc/source/decision_forest/df_reg_dense_batch.cpp
  examples/oneapi/dpc/source/knn/knn_cls_brute_force_dense_batch.cpp
Labels: backport-2021, dpc++

#1042 Fix failed SVM build on gnu510
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
Labels: backport-2021

#1026 [DOC] Updated docs for multiclass
  docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
  docs/source/dev_guide/algorithms/svm_multi_class/multi-class-classifier.rst
Labels: backport-2021, docs

#1060 Added default task for oneAPI kNN train/infer types
  cpp/oneapi/dal/algo/knn/common.hpp
  cpp/oneapi/dal/algo/knn/infer_types.cpp
  cpp/oneapi/dal/algo/knn/infer_types.hpp
  cpp/oneapi/dal/algo/knn/train_types.cpp
  cpp/oneapi/dal/algo/knn/train_types.hpp
Labels: backport-2021

#1065 Jaccard result is in a column major format
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_scalar.hpp
  cpp/oneapi/dal/algo/jaccard/vertex_similarity_types.hpp
  examples/oneapi/cpp/source/example_util/output_helpers.hpp
  examples/oneapi/cpp/source/example_util/output_helpers_graph.hpp
  examples/oneapi/cpp/source/jaccard/jaccard_batch.cpp
Labels: backport-2021

#1063 Add Jaccard Similarity avx512-specific code branch
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_hsw.cpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_scalar.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_skx.cpp
Labels: backport-2021

#1035 Modified DBSCAN algorithm for GPU
  cpp/daal/include/services/internal/sycl/daal_defines_sycl.h
  cpp/daal/src/algorithms/dbscan/dbscan_container.h
  cpp/daal/src/algorithms/dbscan/oneapi/cl_kernels/dbscan_cl_kernels.cl
  cpp/daal/src/algorithms/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
  cpp/daal/src/algorithms/dbscan/oneapi/dbscan_kernel_ucapi.h
Labels: backport-2021

#1080 Fixed mistype in "tech preview" section of the README.md
  README.md
Labels: backport-2021

#1066 add icx config in makefiles
  examples/daal/cpp/makefile_lnx
  examples/daal/cpp/makefile_win
  examples/oneapi/cpp/makefile_lnx
  examples/oneapi/cpp/makefile_win
Labels: backport-2021

#1078 Updated macro to check universal buffer
  cpp/daal/include/services/internal/sycl/daal_defines_sycl.h
Labels: backport-2021

#1082 Fixed KW issue with absent _impl init in vertex_similarity_result constructor
  cpp/oneapi/dal/algo/jaccard/vertex_similarity_types.cpp
  cpp/oneapi/dal/algo/jaccard/vertex_similarity_types.hpp
Labels: backport-2021

#1034 [DOC] Updated knn docs
  docs/source/dev_guide/algorithms/k_nearest_neighbors/k-nearest-neighbors-knn-classifier.rst
Labels: backport-2021, docs

#930 Initial version of tbb env in build
  .ci/env/tbb.bat
  .ci/pipeline/ci.yml
  INSTALL.md
  dev/download_micromkl.bat
  dev/download_tbb.bat
  dev/make/cmplr.clang.mk
  dev/make/cmplr.gnu.mk
  dev/make/cmplr.icc.mk
  dev/make/cmplr.vc.mk
Labels: backport-2021

#1089 Update mklgpufpk to 20201003
  WORKSPACE
  dev/download_micromkl.bat
  dev/download_micromkl.sh
Labels: backport-2021

#1099 Update conda create for daal4py
  .ci/pipeline/ci.yml
Labels: backport-2021, bug

#1070 Added missing checks for GBT GPU implementation (DAAL)
  cpp/daal/src/algorithms/dtrees/gbt/oneapi/cl_kernels/gbt_common_kernels.cl
  cpp/daal/src/algorithms/dtrees/gbt/oneapi/gbt_feature_type_helper_oneapi.h
  cpp/daal/src/algorithms/dtrees/gbt/oneapi/gbt_feature_type_helper_oneapi.i
  cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_tree_impl.h
  cpp/daal/src/algorithms/dtrees/gbt/regression/oneapi/cl_kernels/gbt_batch_regression_kernels.cl
  cpp/daal/src/algorithms/dtrees/gbt/regression/oneapi/gbt_regression_train_dense_default_oneapi_impl.i
  cpp/daal/src/algorithms/dtrees/gbt/regression/oneapi/gbt_regression_train_kernel_oneapi.h
  cpp/daal/src/algorithms/k_nearest_neighbors/oneapi/bf_knn_classification_predict_kernel_ucapi_impl.i
  cpp/daal/src/sycl/cl_kernels/radix_sort.cl
  cpp/daal/src/sycl/sorter.cpp
  cpp/daal/src/sycl/sorter.h
Labels: backport-2021

#1087 DBSCAN kernel split: separate kernels for computation with and w/o we…
  cpp/daal/src/algorithms/dbscan/oneapi/cl_kernels/dbscan_cl_kernels.cl
  cpp/daal/src/algorithms/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
  cpp/daal/src/algorithms/dbscan/oneapi/dbscan_kernel_ucapi.h
Labels: backport-2021

#1107 erase iostream from covariance
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_online_oneapi_impl.i
Labels: backport-2021, bug, dpc++

#1118 Fixed a typo
  README.md
Labels: backport-2021

#1103 added new function setBeta for logistic regression model builder on daal4py side
  cpp/daal/include/algorithms/logistic_regression/logistic_regression_model_builder.h
Labels: backport-2021

#1111 Fixed build issue on VS2017 in Jaccard
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx512.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_hsw.cpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_skx.cpp
Labels: backport-2021

#995 Added safety checks for BF KNN on GPU
  cpp/daal/include/services/internal/sycl/daal_defines_sycl.h
  cpp/daal/src/algorithms/k_nearest_neighbors/oneapi/bf_knn_classification_predict_kernel_ucapi_impl.i
  cpp/daal/src/sycl/select_indexed.cpp
  cpp/daal/src/sycl/select_indexed.h
Labels: backport-2021

#1085 Cov online & batch & distr missed checks
  cpp/daal/src/algorithms/covariance/oneapi/cl_kernels/covariance_kernels.cl
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_batch_oneapi_impl.i
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_distr_step2_oneapi_impl.i
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_online_oneapi_impl.i
  cpp/daal/src/algorithms/covariance/oneapi/covariance_oneapi_impl.i
Labels: backport-2021, dpc++

#1079 [DOC] Updated docs: small fixes
  docs/source/bibliography.rst
  docs/source/dev_guide/algorithms/engines/mt2203.rst
  docs/source/dev_guide/algorithms/implicit_als/implicit-alternating-least-squares.rst
  docs/source/dev_guide/algorithms/kernel_function/kernel-functions.rst
  docs/source/dev_guide/algorithms/lasso_elastic_net/lasso.rst
  docs/source/dev_guide/algorithms/linear_ridge_regression/linear-regression.rst
  docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
  docs/source/dev_guide/algorithms/optimization-solvers/solvers/limited-memory-broyden-fletcher-goldfarb-shanno-algorithm.rst
  docs/source/dev_guide/algorithms/svm/support-vector-machine-classifier.rst
  docs/source/topics/build-examples.rst
Labels: backport-2021, docs

#1115 Remove sequential support from DPC++ examples
  examples/daal/cpp_sycl/daal_win.sln.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
  examples/daal/cpp_sycl/makefile_lnx
  examples/daal/cpp_sycl/makefile_win
  examples/oneapi/dpc/makefile_lnx
Labels: backport-2021

#1125 Safety checks: BlockDescriptor
  cpp/daal/include/data_management/data/numeric_table.h
Labels: backport-2021

#1100 ArrayCopier: offset fix
  cpp/daal/include/services/internal/sycl/types_utils_cxx11.h
Labels: backport-2021

#1142 Added buffer check for multiple types
  cpp/daal/include/services/internal/sycl/daal_defines_sycl.h
  cpp/daal/src/sycl/sorter.cpp
Labels: backport-2021

#1159 [RELEASES] Cov online & batch missed checks (#1085)
  cpp/daal/src/algorithms/covariance/oneapi/cl_kernels/covariance_kernels.cl
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_batch_oneapi_impl.i
  cpp/daal/src/algorithms/covariance/oneapi/covariance_dense_online_oneapi_impl.i
  cpp/daal/src/algorithms/covariance/oneapi/covariance_oneapi_impl.i
Labels: dpc++

#1092 Safety checks: SyclHomogenNumericTable
  cpp/daal/include/data_management/data/internal/numeric_table_sycl_homogen.h
Labels: backport-2021

#1158 Add dal.hpp
  .ci/scripts/clang-format.sh
  cpp/oneapi/.clang-format
  cpp/oneapi/BUILD
  cpp/oneapi/dal.hpp
  cpp/oneapi/dal/BUILD
  cpp/oneapi/dal/backend/dispatcher_cpu.hpp
  dev/bazel/dal.bzl
  makefile
Labels: backport-2021, interfaces, oneAPI

#1122 PCA missed checks
  cpp/daal/src/algorithms/pca/oneapi/cl_kernels/pca_cl_kernels.cl
  cpp/daal/src/algorithms/pca/oneapi/pca_dense_correlation_batch_kernel_ucapi_impl.i
  cpp/daal/src/algorithms/pca/oneapi/pca_dense_correlation_online_kernel_ucapi_impl.i
  cpp/daal/src/algorithms/pca/transform/oneapi/cl_kernels/pca_transform_cl_kernels.cl
  cpp/daal/src/algorithms/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi.h
  cpp/daal/src/algorithms/pca/transform/oneapi/pca_transform_dense_default_batch_oneapi_impl.i
Labels: backport-2021, dpc++

#1119 Safety checks: SyclSoaNumericTable
  cpp/daal/include/data_management/data/internal/numeric_table_sycl_soa.h
  cpp/daal/include/services/internal/sycl/buffer_utils.h
Labels: backport-2021

#1163 Fixed model safety in oneAPI kNN
  cpp/oneapi/dal/algo/knn/backend/model_impl.hpp
Labels: backport-2021

#1131 Checks for K-Means initialization
  cpp/daal/src/algorithms/kmeans/oneapi/kmeans_init_dense_batch_kernel_ucapi.h
  cpp/daal/src/algorithms/kmeans/oneapi/kmeans_init_dense_batch_kernel_ucapi_impl.i
Labels: backport-2021

#1156 Fix minu, maxu vars
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx512.hpp
Labels: backport-2021

#1098 Optimizations for LogLoss & Cross Entropy
  cpp/daal/src/algorithms/logistic_regression/logistic_regression_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_kernel.h
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_kernel.h
  cpp/daal/src/services/service_data_utils.h
Labels: backport-2021

#1173 Remove debug examples for DPCPP
  examples/daal/cpp_sycl/daal_win.sln.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
  examples/oneapi/dpc/onedal_win.sln.tpl
  examples/oneapi/dpc/onedal_win.vcxproj.tpl
  examples/oneapi/dpc/onedal_win.vcxproj.user.tpl
Labels: backport-2021

#1171 Safety checks: Logistic regression
  cpp/daal/include/services/daal_defines.h
  cpp/daal/src/algorithms/logistic_regression/oneapi/cl_kernel/logistic_regression_dense_default.cl
  cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
  cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_train_dense_default_oneapi_impl.i
Labels: backport-2021

#1184 Dev/amk df sf2
  cpp/daal/src/algorithms/dtrees/forest/classification/oneapi/df_classification_train_hist_oneapi_impl.i
  cpp/daal/src/algorithms/dtrees/forest/oneapi/df_feature_type_helper_oneapi.i
  cpp/daal/src/algorithms/dtrees/forest/regression/oneapi/df_regression_train_hist_oneapi_impl.i
Labels: oneAPI

#1140 New library versioning
  cpp/daal/include/services/library_version_info.h
  examples/daal/cpp/daal_win.vcxproj.tpl
  examples/daal/cpp/makefile_win
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/makefile_win
  examples/oneapi/cpp/makefile_win
  examples/oneapi/cpp/onedal_win.vcxproj.tpl
  examples/oneapi/dpc/makefile_win
  examples/oneapi/dpc/onedal_win.vcxproj.tpl
  makefile
  makefile.ver
  samples/daal/cpp/arrow/launcher.bat
  samples/daal/cpp/kdb/launcher.bat
  samples/daal/cpp/mpi/launcher.bat
  samples/daal/cpp/mysql/launcher.bat
Labels: backport-2021

#1182 Overflow checks in detail&backend (oneAPI)
  cpp/oneapi/dal/backend/linalg.hpp
  cpp/oneapi/dal/backend/linalg/matrix.hpp
  cpp/oneapi/dal/detail/common.cpp
  cpp/oneapi/dal/detail/common.hpp
Labels: backport-2021, oneAPI

#1189 Fix dpcpp compile options on Windows
  cpp/daal/src/services/daal_version.h
  cpp/oneapi/dal/dll.rc
  dev/make/deps.mk
Labels: backport-2021, dpc++, oneAPI

#1195 align mesage with daal4py change
  .ci/scripts/conformance-scripts/utils.py
Labels: backport-2021

#1186 Safety checks: SGD and loss functions
  cpp/daal/src/algorithms/objective_function/common/objective_function_utils.i
  cpp/daal/src/algorithms/objective_function/common/oneapi/objective_function_utils_oneapi.h
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/oneapi/cl_kernel/cross_entropy_loss_dense_default.cl
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/oneapi/cross_entropy_loss_dense_default_kernel_oneapi.h
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/oneapi/cross_entropy_loss_dense_default_oneapi_impl.i
  cpp/daal/src/algorithms/objective_function/logistic_loss/oneapi/logistic_loss_dense_default_oneapi_impl.i
  cpp/daal/src/algorithms/optimization_solver/sgd/oneapi/sgd_dense_minibatch_oneapi_impl.i
Labels: backport-2021

#1117 Logistic Regression prediction CPU optimizations
  cpp/daal/src/algorithms/classifier/classifier_predict_fpt.cpp
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/logistic_regression/logistic_regression_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
Labels: backport-2021

#1180 Load graph bug fix
  cpp/oneapi/dal/io/detail/load_graph.hpp
Labels: backport-2021

#1143 [DOC] Updated decision forest chapter
  docs/source/dev_guide/algorithms/decision_forest/decision-forest-classification.rst
  docs/source/dev_guide/algorithms/decision_forest/decision-forest-regression.rst
  docs/source/dev_guide/algorithms/decision_forest/decision-forest.rst
  docs/source/dev_guide/algorithms/decision_forest/index.rst
Labels: backport-2021, docs

#1197 Clean code & add tasks for SVM/Kernel Functions for new interfaces
  cpp/daal/src/algorithms/kernel_function/oneapi/kernel_function_rbf_dense_default_oneapi_impl.i
  cpp/daal/src/algorithms/svm/oneapi/svm_helper_oneapi.h
  cpp/daal/src/algorithms/svm/oneapi/svm_predict_oneapi_impl.i
  cpp/daal/src/algorithms/svm/oneapi/svm_train_cache_oneapi.h
  cpp/daal/src/algorithms/svm/oneapi/svm_train_thunder_oneapi_impl.i
  cpp/daal/src/algorithms/svm/oneapi/svm_train_workset_oneapi.h
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_csr.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel_csr_dpc.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/linear_kernel/common.cpp
  cpp/oneapi/dal/algo/linear_kernel/common.hpp
  cpp/oneapi/dal/algo/linear_kernel/compute_types.cpp
  cpp/oneapi/dal/algo/linear_kernel/compute_types.hpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops_dpc.cpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/cpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/cpu/compute_kernel_csr.cpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/gpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/gpu/compute_kernel_csr_dpc.cpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/rbf_kernel/common.cpp
  cpp/oneapi/dal/algo/rbf_kernel/common.hpp
  cpp/oneapi/dal/algo/rbf_kernel/compute_types.cpp
  cpp/oneapi/dal/algo/rbf_kernel/compute_types.hpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.hpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel.hpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_smo_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/interop_model.hpp
  cpp/oneapi/dal/algo/svm/backend/utils.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.cpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops_dpc.cpp
  cpp/oneapi/dal/algo/svm/infer_types.cpp
  cpp/oneapi/dal/algo/svm/infer_types.hpp
  cpp/oneapi/dal/algo/svm/train_types.cpp
  cpp/oneapi/dal/algo/svm/train_types.hpp
  examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
Labels: backport-2021

#1108 LinReg safety
  cpp/daal/src/algorithms/linear_model/oneapi/cl_kernel/linear_model_prediction.cl
  cpp/daal/src/algorithms/linear_model/oneapi/cl_kernel/reduce_results.cl
  cpp/daal/src/algorithms/linear_model/oneapi/linear_model_predict_dense_default_batch_oneapi_impl.i
  cpp/daal/src/algorithms/linear_model/oneapi/linear_model_train_normeq_finalize_oneapi_impl.i
  cpp/daal/src/algorithms/linear_model/oneapi/linear_model_train_normeq_update_oneapi_impl.i
  cpp/daal/src/algorithms/linear_regression/oneapi/cl_kernel/helper_beta_copy.cl
  cpp/daal/src/algorithms/linear_regression/oneapi/linear_regression_train_dense_normeq_helper_oneapi_impl.i
Labels: backport-2021

#1214 Introduce DALROOT and Major Minor versions in env scripts
  deploy/local/dal
  deploy/local/vars_fbsd.sh
  deploy/local/vars_lnx.sh
  deploy/local/vars_mac.sh
  deploy/local/vars_win.bat
Labels: backport-2021

#1218 SyclHomogenNumericTable: wrong assert removed
  cpp/daal/include/data_management/data/internal/numeric_table_sycl_homogen.h
Labels: backport-2021

#1215 Centralized generator of error messages
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_classification_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_regression_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_classification_dense_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_regression_dense_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/train_ops.hpp
  cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_ops.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/common.cpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
  cpp/oneapi/dal/algo/kmeans/infer_types.cpp
  cpp/oneapi/dal/algo/kmeans/train_types.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/common.cpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_brute_force_classification.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_brute_force_classification.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_kd_tree_classification_dpc.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_kd_tree_classification_dpc.cpp
  cpp/oneapi/dal/algo/knn/common.cpp
  cpp/oneapi/dal/algo/knn/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/knn/detail/train_ops.hpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_svd_dpc.cpp
  cpp/oneapi/dal/algo/pca/common.cpp
  cpp/oneapi/dal/algo/pca/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
  cpp/oneapi/dal/algo/rbf_kernel/common.cpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_smo_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/utils.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/backend/dispatcher_dpc.hpp
  cpp/oneapi/dal/backend/interop/data_conversion.hpp
  cpp/oneapi/dal/backend/interop/error_converter.cpp
  cpp/oneapi/dal/backend/interop/error_converter.hpp
  cpp/oneapi/dal/backend/linalg/matrix.hpp
  cpp/oneapi/dal/detail/array_impl.hpp
  cpp/oneapi/dal/detail/common.cpp
  cpp/oneapi/dal/detail/common.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/graph/graph_service_functions.hpp
  cpp/oneapi/dal/io/csv/detail/read_ops.hpp
  cpp/oneapi/dal/io/detail/load_graph.hpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.cpp
  cpp/oneapi/dal/table/common.cpp
  cpp/oneapi/dal/table/detail/access_wrapper_dpc.hpp
  cpp/oneapi/dal/table/detail/access_wrapper_host.hpp
  cpp/oneapi/dal/test/common.hpp
  cpp/oneapi/dal/test/datasets.cpp
Labels: backport-2021, oneAPI

#1220 Added allocation of SYCL tables for BF KNN in case of GPU run (and other minor changes)
  cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_dense_default_batch_container.h
  cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_result.cpp
  cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_predict_result.h
Labels: backport-2021

#1209 Added checks for oneAPI kNN
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_kd_tree_classification.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_kd_tree_classification.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_brute_force_classification_dpc.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_classification_dpc.cpp
  cpp/oneapi/dal/detail/common.hpp
Labels: backport-2021

#1232 Added overflow check for number of neighbors
  cpp/daal/src/algorithms/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
Labels: backport-2021

#1230 Add badargs tests & safety checks for kf & svm in onedal
  cpp/oneapi/dal/algo/linear_kernel/BUILD
  cpp/oneapi/dal/algo/linear_kernel/common_dpc_test.cpp
  cpp/oneapi/dal/algo/rbf_kernel/BUILD
  cpp/oneapi/dal/algo/rbf_kernel/common_dpc_test.cpp
  cpp/oneapi/dal/algo/rbf_kernel/common_host_test.cpp
  cpp/oneapi/dal/algo/svm/BUILD
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/common_dpc_test.cpp
  cpp/oneapi/dal/algo/svm/common_host_test.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
Labels: backport-2021, dpc++

#1240 Data management: static analysis fixes + allocation check added
  cpp/daal/include/data_management/data/data_dictionary.h
  cpp/oneapi/dal/detail/memory_impl_dpc.hpp
  cpp/oneapi/dal/detail/memory_impl_host.hpp
Labels: backport-2021

#1233 Aligned oneAPI examples and apply clang-format
  .ci/scripts/clang-format.sh
  examples/oneapi/.clang-format
  examples/oneapi/cpp/source/decision_forest/df_cls_dense_batch.cpp
  examples/oneapi/cpp/source/decision_forest/df_reg_dense_batch.cpp
  examples/oneapi/cpp/source/example_util/input_helpers.hpp
  examples/oneapi/cpp/source/graph/graph_service_functions.cpp
  examples/oneapi/cpp/source/graph/load_graph.cpp
  examples/oneapi/cpp/source/jaccard/jaccard_batch.cpp
  examples/oneapi/cpp/source/jaccard/jaccard_batch_app.cpp
  examples/oneapi/cpp/source/kmeans/kmeans_lloyd_dense_batch.cpp
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_dense.cpp
  examples/oneapi/cpp/source/knn/knn_cls_kd_tree_dense_batch.cpp
  examples/oneapi/cpp/source/linear_kernel/linear_kernel_dense_batch.cpp
  examples/oneapi/cpp/source/pca/pca_dense_batch.cpp
  examples/oneapi/cpp/source/rbf_kernel/rbf_kernel_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/cpp/source/table/column_accessor_homogen.cpp
  examples/oneapi/dpc/source/decision_forest/df_cls_dense_batch.cpp
  examples/oneapi/dpc/source/decision_forest/df_reg_dense_batch.cpp
  examples/oneapi/dpc/source/example_util/dpc_helpers.hpp
  examples/oneapi/dpc/source/example_util/input_helpers.hpp
  examples/oneapi/dpc/source/example_util/output_helpers.hpp
  examples/oneapi/dpc/source/kmeans/kmeans_lloyd_dense_batch.cpp
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_dense.cpp
  examples/oneapi/dpc/source/knn/knn_cls_brute_force_dense_batch.cpp
  examples/oneapi/dpc/source/linear_kernel/linear_kernel_dense_batch.cpp
  examples/oneapi/dpc/source/pca/pca_cor_dense_batch.cpp
  examples/oneapi/dpc/source/rbf_kernel/rbf_kernel_dense_batch.cpp
  examples/oneapi/dpc/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/dpc/source/table/column_accessor_homogen.cpp
Labels: backport-2021, oneAPI

#1228 Added tests for oneAPI kNN
  cpp/oneapi/dal/algo/knn/BUILD
  cpp/oneapi/dal/algo/knn/common_knn_dpc_test.cpp
  cpp/oneapi/dal/algo/knn/common_knn_host_test.cpp
Labels: backport-2021, dpc++, oneAPI

#1222 fix conformance for PCA, KMeans and KMeans init constructors
  cpp/oneapi/dal/algo/kmeans/common.hpp
  cpp/oneapi/dal/algo/kmeans_init/common.hpp
  cpp/oneapi/dal/algo/pca/common.hpp
Labels: backport-2021, dpc++, oneAPI
