Repository uxlfoundation/oneDAL, pull requests merged in 2020-09, with the labels that each got.

#878 Add --gcc-toolchain flag for clang on Linux
  dev/make/common.mk
  makefile
Labels: backport-2021

#881 bulkload renovate updates on dependencies
  docs/requirements.txt
  docs/source/topics/generic-workflow.rst
Labels: backport-2021

#770 [DOC] Conversion: distributed K-Means
  docs/source/dev_guide/algorithms/kmeans/computation-batch.rst
  docs/source/dev_guide/algorithms/kmeans/computation-distributed.rst
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-computation-step-1.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-computation-step-2.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-plusPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-1-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-1-plusPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-2-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-2-plusPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-3-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-3-plusPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-4-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-4-plusPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/images/kmeans-distributed-init-step-5-parallelPlus-methods.png
  docs/source/dev_guide/algorithms/kmeans/includes/computation-distributed.rst
  docs/source/dev_guide/algorithms/kmeans/includes/initialization-distributed.rst
  docs/source/dev_guide/algorithms/kmeans/initialization-batch.rst
  docs/source/dev_guide/algorithms/kmeans/initialization-distributed.rst
  docs/source/dev_guide/algorithms/kmeans/k-means-clustering.rst
Labels: docs

#889 [DOC] Updated oneAPI DPC++ Compiler name
  INSTALL.md
  docs/source/conf.py
  docs/source/notes/issues/2021.1-beta06/includes/note-refer-to-dpcpp-level-zero.rst
  docs/source/notes/issues/2021.1-beta06/incorrect-linker-behavior.rst
  docs/source/notes/known_issues.rst
  docs/source/topics/build-examples.rst
  docs/source/topics/prerequisites.rst
Labels: backport-2021, docs

#710 Optimize rbf & linear kernel for SOA table result
  cpp/daal/include/data_management/data/soa_numeric_table.h
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
  cpp/daal/src/data_management/soa_numeric_table.cpp
  cpp/daal/src/externals/service_blas.h
Labels: perf

#896 conformance between spec and API: kmeans_init
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/common.cpp
  cpp/oneapi/dal/algo/kmeans_init/common.hpp
  cpp/oneapi/dal/algo/kmeans_init/compute_types.cpp
  cpp/oneapi/dal/algo/kmeans_init/compute_types.hpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops_dpc.cpp
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_dense.cpp
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_dense.cpp
Labels: dpc++, interfaces

#792 Support decision function for multiclass
  cpp/daal/include/algorithms/multi_class_classifier/multi_class_classifier_model.h
  cpp/daal/include/algorithms/multi_class_classifier/multi_class_classifier_predict.h
  cpp/daal/include/algorithms/multi_class_classifier/multi_class_classifier_predict_types.h
  cpp/daal/include/services/daal_defines.h
  cpp/daal/src/algorithms/multiclassclassifier/inner/multiclassclassifier_predict_batch_container_v1.h
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_batch_container.h
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_kernel.h
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_mccwu_impl.i
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_mccwu_kernel.h
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_result.cpp
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_result_fpt.cpp
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_votebased_impl.i
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/daal/src/services/daal_strings.h
  examples/daal/cpp/source/svm/svm_multi_class_boser_csr_batch.cpp
  examples/daal/cpp/source/svm/svm_multi_class_boser_dense_batch.cpp
  examples/daal/cpp/source/svm/svm_multi_class_thunder_csr_batch.cpp
  examples/daal/cpp/source/svm/svm_multi_class_thunder_dense_batch.cpp
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassModelBuilder.java
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassThunderCSRBatch.java
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassThunderDenseBatch.java
  java/com/intel/daal/algorithms/multi_class_classifier/ResultsToComputeId.java
  java/com/intel/daal/algorithms/multi_class_classifier/predict_result.cpp
  java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionBatch.java
  java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionResult.java
  java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionResultId.java
Labels: interfaces

#905 [mnt] Optimize rbf & linear kernel for SOA table result / Support decision function for multiclass
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/multiclassclassifier/inner/multiclassclassifier_predict_batch_container_v1.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_model.cpp
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_batch_container.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_kernel.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_mccwu_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_mccwu_kernel.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_result.cpp
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_result_fpt.cpp
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_votebased_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
  algorithms/kernel/svm/svm_train_batch_container.h
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_cache.h
  examples/cpp/source/svm/svm_multi_class_boser_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_boser_dense_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_dense_batch.cpp
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassModelBuilder.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassModelBuilder.java
  externals/service_blas.h
  include/algorithms/multi_class_classifier/multi_class_classifier_model.h
  include/algorithms/multi_class_classifier/multi_class_classifier_predict.h
  include/algorithms/multi_class_classifier/multi_class_classifier_predict_types.h
  include/data_management/data/soa_numeric_table.h
  include/services/daal_defines.h
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/ModelBuilder.java
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/ResultsToComputeId.java
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionBatch.java
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionResult.java
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/prediction/PredictionResultId.java
  lang_interface/java/com/intel/daal/algorithms/multi_class_classifier/training/TrainingResult.java
  lang_service/java/com/intel/daal/algorithms/multi_class_classifier/predict_result.cpp
  service/kernel/daal_strings.h
  service/kernel/data_management/soa_numeric_table.cpp
  service/kernel/service_data_utils.h
Labels: backport-2020

#902 [DOC] Updated links to Intel website
  INSTALL.md
  README.md
  docs/source/build_app/build-application.rst
  docs/source/dev_guide/algorithms/gradient_boosted_trees/gradient-boosted-trees.rst
  docs/source/dev_guide/algorithms/linear_ridge_regression/linear-ridge-regression-computation.rst
  docs/source/dev_guide/algorithms/logistic_regression/logistic-regression.rst
  docs/source/dev_guide/algorithms/naive_bayes/computation-batch.rst
  docs/source/dev_guide/algorithms/optimization-solvers/solvers/limited-memory-broyden-fletcher-goldfarb-shanno-algorithm.rst
  docs/source/dev_guide/algorithms/optimization-solvers/solvers/stochastic-gradient-descent-algorithm.rst
  docs/source/dev_guide/algorithms/svm_multi_class/multi-class-classifier.rst
  docs/source/index.rst
  docs/source/topics/installation.rst
Labels: backport-2021, docs

#913 Fix prints for java examples
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
Labels: backport-2020

#921 [Part2] Optimize rbf & linear kernel for SOA table result
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_kernel.h
  cpp/daal/src/algorithms/svm/svm_predict_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
Labels: backport-2021, perf

#922 [mnt][Part2] Optimize rbf & linear kernel for SOA table result
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_kernel.h
  algorithms/kernel/svm/svm_predict_impl.i
  algorithms/kernel/svm/svm_train_thunder_cache.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_kernel.h
Labels: backport-2020

#923 RF minor performance optimizations
  algorithms/kernel/dtrees/forest/classification/df_classification_train_dense_default_impl.i
  algorithms/kernel/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Labels: perf

#931 oneAPI kmeans_init minor fix
  cpp/oneapi/dal/algo/kmeans_init/common.hpp
Labels: backport-2021, bug, dpc++

#914 Fix daal4py tests in public CI
  .ci/pipeline/ci.yml
  .ci/scripts/daal4py_test.sh
Labels: backport-2020, backport-2021

#894 Conformance between spec and API: error hadnling
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_dpc.cpp
  cpp/oneapi/dal/backend/interop/error_converter.cpp
  cpp/oneapi/dal/exceptions.cpp
  cpp/oneapi/dal/exceptions.hpp
  cpp/oneapi/dal/io/detail/load_graph.hpp
Labels: backport-2021, dpc++, interfaces

#964 [DOC] Added known issues for beta09
  docs/source/notes/issues/2021.1-beta09/oneapi-examples-segfault.rst
  docs/source/notes/issues/2021.1-beta09/pca-examples-on-gpu.rst
  docs/source/notes/known_issues.rst
Labels: backport-2021, docs

#965 Examples update - cleanup debug.static and 32 bit
  deploy/local/generate_win_solution.py
  examples/daal/cpp/daal_win.sln.tpl
  examples/daal/cpp/daal_win.vcxproj.tpl
  examples/daal/cpp/daal_win.vcxproj.user.tpl
  examples/daal/cpp_sycl/daal_win.sln.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
  examples/oneapi/cpp/daal_win.sln.tpl
Labels: backport-2021

#959 Knn: set_data_use_in_model parameter removed
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_kd_tree.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_kd_tree.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_brute_force_dpc.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel_brute_force_dpc.cpp
  cpp/oneapi/dal/algo/knn/common.cpp
  cpp/oneapi/dal/algo/knn/common.hpp
  examples/oneapi/cpp/source/knn/knn_cls_kd_tree_dense_batch.cpp
  examples/oneapi/dpc/source/knn/knn_cls_brute_force_dense_batch.cpp
Labels: backport-2021, interfaces

#970 Enable PRODUCT_STATUS update for headers version
  cpp/daal/include/services/library_version_info.h
  makefile.ver
Labels: backport-2021

#979 [DOC] Updated links to examples
  docs/source/dev_guide/algorithms/k_nearest_neighbors/k-nearest-neighbors-knn-classifier.rst
  docs/source/dev_guide/algorithms/kmeans/k-means-clustering.rst
Labels: backport-2021, docs

#906 USM support for accessors
  cpp/oneapi/dal/backend/interop/data_conversion.hpp
  cpp/oneapi/dal/table/backend/convert.cpp
  cpp/oneapi/dal/table/backend/convert.hpp
  cpp/oneapi/dal/table/backend/empty_table_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_table_builder_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.cpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.hpp
  cpp/oneapi/dal/table/column_accessor_dpc_test.cpp
Labels: backport-2021, dpc++

#909 Conformance between spec and API: kmeans
  cpp/oneapi/dal/algo/kmeans/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/train_kernel.hpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/train_kernel_lloyd_dense.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/common.cpp
  cpp/oneapi/dal/algo/kmeans/common.hpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops.cpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.cpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/infer_types.cpp
  cpp/oneapi/dal/algo/kmeans/infer_types.hpp
  cpp/oneapi/dal/algo/kmeans/train_types.cpp
  cpp/oneapi/dal/algo/kmeans/train_types.hpp
Labels: backport-2021, dpc++, interfaces

#1001 Minor Fixes in kNN, SVM, and Compression Stream
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_impl.i
  cpp/daal/src/services/compression/compression_stream.cpp
  examples/daal/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
Labels: backport-2021

#1006 fixed clear code
  examples/oneapi/cpp/source/jaccard/jaccard_batch_app.cpp
Labels: backport-2021

#996 [DOC] Fixed wording in docs
  docs/source/_static/style.css
  docs/source/contribution/coding_guide.rst
  docs/source/cpu-vs-gpu.rst
  docs/source/dev_guide/algorithms/normalization/z-score.rst
  docs/source/dev_guide/usage/algorithms.rst
  docs/source/dev_guide/usage/computation-modes.rst
Labels: backport-2021, docs

#1010 Clean code for SVM
  cpp/daal/src/algorithms/elastic_net/elastic_net_train_dense_default_impl.i
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
  cpp/daal/src/algorithms/logistic_regression/oneapi/logistic_regression_train_dense_default_oneapi_impl.i
  cpp/daal/src/algorithms/svm/inner/svm_train_batch_container_v1.h
  cpp/daal/src/algorithms/svm/inner/svm_train_boser_batch_fpt_cpu_v1.cpp
  cpp/daal/src/algorithms/svm/oneapi/svm_helper_oneapi.h
  cpp/daal/src/algorithms/svm/oneapi/svm_predict_oneapi_impl.i
  cpp/daal/src/algorithms/svm/oneapi/svm_train_thunder_kernel_oneapi.h
  cpp/daal/src/algorithms/svm/oneapi/svm_train_thunder_oneapi_impl.i
  cpp/daal/src/algorithms/svm/oneapi/svm_train_workset_oneapi.h
  cpp/daal/src/algorithms/svm/svm_train_batch_container.h
  cpp/daal/src/algorithms/svm/svm_train_boser_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/svm/svm_train_boser_impl.i
  cpp/daal/src/algorithms/svm/svm_train_boser_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/svm/svm_train_thunder_batch_oneapi_fpt.cpp
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
  cpp/daal/src/externals/service_blas.h
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
  examples/daal/cpp_sycl/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/dpc/source/svm/svm_two_class_thunder_dense_batch.cpp
Labels: backport-2021

#1018 Fix for GBT cls prediction with mismatched types(like PR#294)
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_dense_default_batch_impl.i
Labels: backport-2021
