Repository uxlfoundation/oneDAL, pull requests merged in 2020-06, with the labels that each got.

#556 Fix memory allocation in SVM Predict & Performance optimization
  algorithms/kernel/svm/svm_predict_impl.i
Labels: bug, perf

#615 [Part2] Implemented Thunder method for SVM algorithm on CPU
  examples/cpp/DAALExamples.sln
  examples/cpp/daal_fbsd.lst
  examples/cpp/daal_lnx.lst
  examples/cpp/daal_mac.lst
  examples/cpp/source/svm/svm_multi_class_boser_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_boser_dense_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_dense_batch.cpp
  examples/cpp/source/svm/svm_two_class_boser_csr_batch.cpp
  examples/cpp/source/svm/svm_two_class_boser_dense_batch.cpp
  examples/cpp/source/svm/svm_two_class_model_builder.cpp
  examples/cpp/source/svm/svm_two_class_thunder_csr_batch.cpp
  examples/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.user
  examples/cpp_sycl/source/svm/svm_two_class_dense_batch.cpp
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassBoserDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassThunderCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassThunderDenseBatch.java
  examples/java/daal.lst.bat
  examples/java/daal_fbsd.lst
  examples/java/daal_lnx.lst
  examples/java/daal_mac.lst
  lang_interface/java/com/intel/daal/algorithms/svm/training/TrainingBatch.java
  lang_interface/java/com/intel/daal/algorithms/svm/training/TrainingMethod.java
  lang_service/java/com/intel/daal/algorithms/svm/train.cpp
Labels: new algorithm

#614 Optimize compute RBF Kernel for Matrix to Matrix case
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/kernel_function/oneapi/kernel_function_rbf_dense_default_oneapi_impl.i
Labels: perf

#623 [Part2] Implemented Thunder method for SVM algorithm on CPU
  examples/cpp/DAALExamples.sln
  examples/cpp/daal_fbsd.lst
  examples/cpp/daal_lnx.lst
  examples/cpp/daal_mac.lst
  examples/cpp/source/svm/svm_multi_class_boser_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_boser_dense_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_csr_batch.cpp
  examples/cpp/source/svm/svm_multi_class_thunder_dense_batch.cpp
  examples/cpp/source/svm/svm_two_class_boser_csr_batch.cpp
  examples/cpp/source/svm/svm_two_class_boser_dense_batch.cpp
  examples/cpp/source/svm/svm_two_class_model_builder.cpp
  examples/cpp/source/svm/svm_two_class_thunder_csr_batch.cpp
  examples/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.filters
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.user
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassBoserDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMMultiClassThunderDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassBoserCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassBoserDenseBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassThunderCSRBatch.java
  examples/java/com/intel/daal/examples/svm/SVMTwoClassThunderDenseBatch.java
  examples/java/daal.lst.bat
  examples/java/daal_fbsd.lst
  examples/java/daal_lnx.lst
  examples/java/daal_mac.lst
  lang_interface/java/com/intel/daal/algorithms/svm/training/TrainingBatch.java
  lang_interface/java/com/intel/daal/algorithms/svm/training/TrainingMethod.java
  lang_service/java/com/intel/daal/algorithms/svm/train.cpp
Labels: promote to releases

#627 Optimize compute RBF Kernel for Matrix to Matrix case
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
Labels: promote to releases

#628 Fix SVM predict not deterministic result & small refactor
  algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/kmeans/kmeans_lloyd_postprocessing.h
  algorithms/kernel/svm/svm_predict_impl.i
  algorithms/kernel/svm/svm_train_boser_impl.i
  algorithms/kernel/svm/svm_train_common_avx512_impl.i
  algorithms/kernel/svm/svm_train_common_impl.i
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_workset.h
  examples/cpp/source/svm/svm_two_class_model_builder.cpp
  externals/service_blas.h
Labels: bug

#634 Fix memory allocation in SVM Predict & Performance optimization & small refactor
  algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/kmeans/kmeans_lloyd_postprocessing.h
  algorithms/kernel/svm/svm_predict_impl.i
  algorithms/kernel/svm/svm_train_common_avx512_impl.i
  algorithms/kernel/svm/svm_train_common_impl.i
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_workset.h
  examples/cpp/source/svm/svm_two_class_model_builder.cpp
  externals/service_blas.h
Labels: promote to releases

#639 [mnt] Support weights for SVM and Multiclass
  algorithms/kernel/multiclassclassifier/inner/multiclassclassifier_train_batch_container_v1.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_batch_container.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_kernel.h
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
  algorithms/kernel/svm/inner/svm_train_batch_container_v1.h
  algorithms/kernel/svm/svm_train_batch_container.h
  algorithms/kernel/svm/svm_train_boser_impl.i
  algorithms/kernel/svm/svm_train_boser_kernel.h
  algorithms/kernel/svm/svm_train_kernel.h
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_kernel.h
  algorithms/kernel/svm/svm_train_thunder_workset.h
Labels: promote to releases

#641 Fix bugs for compute of Bias; Add support labels 0 and 1; Increase minimum out iterations
  algorithms/kernel/svm/svm_train_boser_impl.i
  algorithms/kernel/svm/svm_train_kernel.h
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_workset.h
Labels: bug, promote to releases

#648 [mnt] LRU cache for thunder method of SVM
  algorithms/kernel/service_hash_table.h
  algorithms/kernel/svm/svm_train_common.h
  algorithms/kernel/svm/svm_train_common_impl.i
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_cache.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_kernel.h
  algorithms/kernel/svm/svm_train_thunder_workset.h
  include/data_management/data/soa_numeric_table.h
  service/kernel/data_management/service_numeric_table.h
  service/kernel/data_management/soa_numeric_table.cpp
Labels: promote to releases

#651 Add targets to build the new C++ part
  .ci/scripts/build.sh
  cpp/daal/include/sycl/internal/execution_context.h
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/backend/dispatcher.hpp
  cpp/oneapi/dal/backend/dispatcher_cpu.hpp
  cpp/oneapi/dal/backend/interop/common.hpp
  cpp/oneapi/dal/backend/interop/data_conversion.hpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
  cpp/oneapi/dal/data/table_builder.hpp
  cpp/oneapi/dal/execution_context.cpp
  cpp/oneapi/dal/util/type_traits.hpp
  dev/make/cmplr.gnu.mk
  dev/make/common.mk
  examples/oneapi/cpp/daal_lnx.lst
  examples/oneapi/cpp/makefile_lnx
  makefile
Labels: dpc++

#658 [mnt-rls] LRU cache for thunder method of SVM (#648)
  algorithms/kernel/service_hash_table.h
  algorithms/kernel/svm/svm_train_common.h
  algorithms/kernel/svm/svm_train_common_impl.i
  algorithms/kernel/svm/svm_train_result.h
  algorithms/kernel/svm/svm_train_thunder_cache.h
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_kernel.h
  algorithms/kernel/svm/svm_train_thunder_workset.h
  include/data_management/data/soa_numeric_table.h
  service/kernel/data_management/service_numeric_table.h
  service/kernel/data_management/soa_numeric_table.cpp
Labels: promote to releases

#664 Fix compilers warnings
  algorithms/kernel/svm/svm_train_common_impl.i
Labels: bug, promote to releases

#662 Fix compilers warnings
  algorithms/kernel/svm/svm_train_common_impl.i
Labels: bug, promote to releases

#671 Fix path in vcproj for SVM
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_metrics_dense_batch/svm_multi_class_metrics_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_model_builder/svm_multi_class_model_builder.vcxproj
  examples/cpp/vcproj/svm_multi_class_model_builder/svm_multi_class_model_builder.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_metrics_dense_batch/svm_two_class_metrics_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_model_builder/svm_two_class_model_builder.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.user
Labels: bug, promote to releases

#670 Fix path in vcproj for SVM
  examples/cpp/vcproj/svm_multi_class_boser_csr_batch/svm_multi_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_boser_dense_batch/svm_multi_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_metrics_dense_batch/svm_multi_class_metrics_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_model_builder/svm_multi_class_model_builder.vcxproj
  examples/cpp/vcproj/svm_multi_class_model_builder/svm_multi_class_model_builder.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_csr_batch/svm_multi_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_multi_class_thunder_dense_batch/svm_multi_class_thunder_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_csr_batch/svm_two_class_boser_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_boser_dense_batch/svm_two_class_boser_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_metrics_dense_batch/svm_two_class_metrics_dense_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_model_builder/svm_two_class_model_builder.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_csr_batch/svm_two_class_thunder_csr_batch.vcxproj.user
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj
  examples/cpp/vcproj/svm_two_class_thunder_dense_batch/svm_two_class_thunder_dense_batch.vcxproj.user
Labels: bug, promote to releases

#679 DPC++ support for dal::array
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/data/accessor_test.cpp
  cpp/oneapi/dal/data/array.hpp
  cpp/oneapi/dal/data/array_dpc_test.cpp
  cpp/oneapi/dal/data/array_test.cpp
  cpp/oneapi/dal/data/backend/homogen_table_impl.cpp
  cpp/oneapi/dal/data/backend/homogen_table_impl.hpp
  cpp/oneapi/dal/data/table_builder_test.cpp
  cpp/oneapi/dal/data/table_metadata.cpp
  cpp/oneapi/dal/data/table_test.cpp
  cpp/oneapi/dal/detail/common.hpp
  cpp/oneapi/dal/detail/common_dpc.hpp
  cpp/oneapi/dal/detail/memory.hpp
  cpp/oneapi/dal/detail/memory_impl_dpc.hpp
  cpp/oneapi/dal/detail/memory_impl_host.hpp
Labels: dpc++
