Repository uxlfoundation/oneDAL, pull requests merged in 2020-07, with the labels that each got.

#696 Update gpu example for svm
  examples/daal/cpp_sycl/daal_lnx.lst
  examples/daal/cpp_sycl/source/svm/svm_two_class_thunder_dense_batch.cpp
Labels: dpc++

#694 Added knn algorithm for oneAPI
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_predict_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_batch_fpt_cpu.cpp
  cpp/oneapi/dal/algo/knn.hpp
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_kd_tree.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel.hpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_kd_tree.cpp
  cpp/oneapi/dal/algo/knn/backend/gpu/train_kernel.hpp
  cpp/oneapi/dal/algo/knn/backend/model_interop.hpp
  cpp/oneapi/dal/algo/knn/common.cpp
  cpp/oneapi/dal/algo/knn/common.hpp
  cpp/oneapi/dal/algo/knn/detail/infer_ops.cpp
  cpp/oneapi/dal/algo/knn/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/knn/detail/model_impl.hpp
  cpp/oneapi/dal/algo/knn/detail/train_ops.cpp
  cpp/oneapi/dal/algo/knn/detail/train_ops.hpp
  cpp/oneapi/dal/algo/knn/infer.hpp
  cpp/oneapi/dal/algo/knn/infer_types.cpp
  cpp/oneapi/dal/algo/knn/infer_types.hpp
  cpp/oneapi/dal/algo/knn/train.hpp
  cpp/oneapi/dal/algo/knn/train_types.cpp
  cpp/oneapi/dal/algo/knn/train_types.hpp
  cpp/oneapi/dal/detail/common.hpp
  examples/oneapi/cpp/daal_lnx.lst
  examples/oneapi/cpp/makefile_lnx
  examples/oneapi/cpp/source/knn/knn_cls_kd_tree_dense_batch.cpp
  makefile.lst
Labels: dpc++

#676 oneDAL error handling impl
  cpp/daal/include/services/error_handling.h
  cpp/daal/include/services/error_indexes.h
  cpp/daal/include/services/internal/status_to_error_id.h
  cpp/daal/src/services/error_handling.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/backend/interop/error_converter.hpp
  cpp/oneapi/dal/exceptions.cpp
  cpp/oneapi/dal/exceptions.hpp
Labels: dpc++

#682 new interfaces (train and infer) for df classifier
  cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model_impl.h
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch.h
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_hist_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_model_impl.h
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_predict_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/services/service_algo_utils.h
  cpp/oneapi/dal/algo/decision_forest.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_classification_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_regression_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_classification_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_regression_hist.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/interop_helpers.hpp
  cpp/oneapi/dal/algo/decision_forest/common.cpp
  cpp/oneapi/dal/algo/decision_forest/common.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/infer_ops.cpp
  cpp/oneapi/dal/algo/decision_forest/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/detail/model_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/train_ops.cpp
  cpp/oneapi/dal/algo/decision_forest/detail/train_ops.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/train_ops_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/infer.hpp
  cpp/oneapi/dal/algo/decision_forest/infer_types.cpp
  cpp/oneapi/dal/algo/decision_forest/infer_types.hpp
  cpp/oneapi/dal/algo/decision_forest/train.hpp
  cpp/oneapi/dal/algo/decision_forest/train_types.cpp
  cpp/oneapi/dal/algo/decision_forest/train_types.hpp
  examples/oneapi/cpp/daal_lnx.lst
  examples/oneapi/cpp/makefile_lnx
  examples/oneapi/cpp/source/decision_forest/df_cls_dense_batch.cpp
  examples/oneapi/cpp/source/decision_forest/df_reg_dense_batch.cpp
  makefile.lst
Labels: dpc++

#714 Change level0 header name
  cpp/daal/include/sycl/internal/kernel_scheduler_sycl.h
Labels: dpc++

#715 Error handling for SVM algorithms
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/rbf_kernel/common.cpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_smo_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
Labels: dpc++

#702 Fix illegal instruction for service internal SOA
  cpp/daal/include/data_management/data/soa_numeric_table.h
  cpp/daal/src/data_management/service_numeric_table.h
  cpp/daal/src/data_management/soa_numeric_table.cpp
Labels: bug

#733 oneAPI PCA error handling
  cpp/oneapi/dal/algo/pca/common.cpp
  cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
Labels: dpc++, promote to releases

#739 [RELEASES] Fix nmake issue
  examples/daal/cpp/makefile_win
  examples/daal/cpp_sycl/makefile_win
  examples/oneapi/cpp/makefile_win
Labels: bug, dpc++, duplicate

#736 Fix nmake issue
  examples/daal/cpp/makefile_win
  examples/daal/cpp_sycl/makefile_win
  examples/oneapi/cpp/makefile_win
Labels: bug

#737 [RELEASES] oneAPI PCA error handling (#733)
  cpp/oneapi/dal/algo/pca/common.cpp
  cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
Labels: dpc++, duplicate, promote to releases

#741 [beta08] Remove sse3 on mac (#740)
  cpp/daal/src/externals/service_blas_mkl.h
  cpp/daal/src/externals/service_lapack_mkl.h
  cpp/daal/src/externals/service_spblas_mkl.h
  cpp/daal/src/externals/service_stat_rng_mkl.h
  dev/make/cmplr.icc.mk
Labels: duplicate

#725 [mnt] fix observationsPerTreeFraction in GBT regression
  algorithms/kernel/dtrees/gbt/gbt_train_dense_default_impl.i
Labels: bug

#731 Fix illegal instruction for service internal SOA
  include/data_management/data/soa_numeric_table.h
  service/kernel/data_management/service_numeric_table.h
  service/kernel/data_management/soa_numeric_table.cpp
Labels: promote to releases

#763 Update reference for example in docs & fix minor mistakes
  docs/source/dev_guide/algorithms/kernel_function/kernel-functions.rst
  docs/source/dev_guide/algorithms/svm/support-vector-machine-classifier.rst
  docs/source/dev_guide/algorithms/svm_multi_class/multi-class-classifier.rst
Labels: docs

#766 [DOC] Updated known issues for beta08,
  docs/source/_static/style.css
  docs/source/notes/issues/2021.1-beta08/windows-static-debug-config.rst
  docs/source/notes/known_issues.rst
Labels: docs

#768 [DOC] Fixed paths to examples
  docs/source/build_app/build-application.rst
  docs/source/topics/build-examples.rst
Labels: docs
