Repository uxlfoundation/oneDAL, pull requests merged in 2020-11, with the labels that each got.

#1255 Library Versioning Fix
  cpp/daal/include/daal_win.h
  cpp/daal/src/externals/core_threading_win_dll.cpp
  cpp/daal/src/services/dll.rc
  makefile
Labels: backport-2021

#1242 added overflow checks and corresponding casts
  cpp/oneapi/dal/algo/kmeans/BUILD
  cpp/oneapi/dal/algo/kmeans/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/train_kernel_lloyd_dense.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_dense_dpc_test.cpp
  cpp/oneapi/dal/algo/kmeans/common_kmeans_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/BUILD
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/common_kmeans_init_test.cpp
  cpp/oneapi/dal/algo/pca/BUILD
  cpp/oneapi/dal/algo/pca/backend/cpu/common_test.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_svd.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/common_dpc_test.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov_dpc.cpp
  cpp/oneapi/dal/algo/pca/common_pca_test.cpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
Labels: backport-2021, oneAPI

#1231 Added missing checks in OneDAL tables
  cpp/oneapi/dal/detail/common.cpp
  cpp/oneapi/dal/table/column_accessor_dpc_test.cpp
  cpp/oneapi/dal/table/column_accessor_test.cpp
  cpp/oneapi/dal/table/common_test.cpp
  cpp/oneapi/dal/table/homogen.hpp
  cpp/oneapi/dal/table/homogen_test.cpp
  cpp/oneapi/dal/table/row_accessor_dpc_test.cpp
  cpp/oneapi/dal/table/row_accessor_test.cpp
Labels: backport-2021

#1261 Using safe arithmetic in graph
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx2.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_avx512.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_hsw.cpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_scalar.hpp
  cpp/oneapi/dal/algo/jaccard/backend/cpu/vertex_similarity_default_kernel_skx.cpp
  cpp/oneapi/dal/algo/jaccard/common.hpp
  cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_ops.cpp
  cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_ops.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/detail/vertex_similarity_ops.hpp
  cpp/oneapi/dal/io/detail/load_graph.hpp
Labels: backport-2021

#1274 change compiler for sycl examples
  examples/daal/cpp_sycl/makefile_lnx
  examples/daal/cpp_sycl/makefile_win
Labels: backport-2021

#1277 enable knn on CPU for sycl_examples
  examples/daal/cpp_sycl/source/k_nearest_neighbors/bf_knn_dense_batch.cpp
Labels: backport-2021

#1270 Fix argmax kernel for GPU SVM
  cpp/daal/src/algorithms/svm/oneapi/cl_kernels/svm_train_block_smo_oneapi.cl
  cpp/daal/src/algorithms/svm/oneapi/svm_train_result_oneapi.h
Labels: backport-2021, bug, dpc++

#1271 Fix build issue for GCC compiler
  cpp/daal/src/externals/service_service_mkl.h
Labels: backport-2021

#1266 [DOC] Binary versions info
  docs/source/build_app/build-application.rst
Labels: backport-2021, docs

#1291 Performance optimization for SVM predict
  cpp/daal/src/algorithms/kernel_function/kernel_function_linear_dense_default_impl.i
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/service_threading.h
  cpp/daal/src/algorithms/svm/svm_predict_impl.i
  cpp/daal/src/externals/service_blas.h
  cpp/daal/src/externals/service_spblas.h
  cpp/daal/src/threading/threading.h
Labels: perf

#1284 [DOC] Updated readme and contributing files
  CONTRIBUTING.md
  README.md
Labels: backport-2021, docs

#1289 Fix array size in sycl SOA
  cpp/daal/include/data_management/data/internal/numeric_table_sycl_soa.h
Labels: backport-2021, bug, dpc++
