Repository uxlfoundation/oneDAL, pull requests merged in 2020-08, with the labels that each got.

#773 Fix count subvectors for multiclass SVM for CSR data
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_predict_votebased_impl.i
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
  cpp/daal/src/algorithms/svm/svm_predict_impl.i
  cpp/daal/src/data_management/service_numeric_table.h
Labels: bug

#785 Mergre missed changes from master & Fix count subvectors for multiclass SVM for CSR data
  algorithms/kernel/kernel_function/kernel_function_linear_csr_fast_impl.i
  algorithms/kernel/kernel_function/kernel_function_linear_dense_default_impl.i
  algorithms/kernel/kernel_function/kernel_function_rbf_csr_fast_impl.i
  algorithms/kernel/kernel_function/kernel_function_rbf_dense_default_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_predict_votebased_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
  algorithms/kernel/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
  algorithms/kernel/svm/svm_predict_batch_container.h
  algorithms/kernel/svm/svm_predict_impl.i
  algorithms/kernel/svm/svm_predict_kernel.h
  algorithms/kernel/svm/svm_train.cpp
  algorithms/kernel/svm/svm_train_boser_cache.i
  algorithms/kernel/svm/svm_train_boser_impl.i
  algorithms/kernel/svm/svm_train_thunder_impl.i
  algorithms/kernel/svm/svm_train_thunder_kernel.h
  algorithms/kernel/svm/svm_train_thunder_workset.h
  service/kernel/data_management/service_numeric_table.h
Labels: promote to releases

#793 erase extra dependencies from error handling
  cpp/oneapi/dal/exceptions.hpp
Labels: dpc++, interfaces

#631 [master] Removing conversions for SOA tables in Finite Check
  cpp/daal/src/data_management/finiteness_checker.cpp
  cpp/daal/src/externals/core_threading_win_dll.cpp
  cpp/daal/src/threading/threading.cpp
  cpp/daal/src/threading/threading.h
Labels: perf

#638 [mnt] Removing conversions for SOA tables in Finite Check
  algorithms/threading/threading.cpp
  algorithms/threading/threading.h
  externals/core_threading_win_dll.cpp
  service/kernel/data_management/finiteness_checker.cpp
Labels: perf

#835 Reduce of calls memory allocate for cache in SVM
  cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
Labels: perf

#831 Fix conformance testing
  .ci/scripts/conformance-scripts/download_tests.sh
  .ci/scripts/conformance-scripts/run_tests.py
  .ci/scripts/conformance-scripts/utils.py
  .ci/scripts/conformance_test.sh
Labels: backport-2020, backport-2021

#843 [mnt] Reduce of calls memory allocate for cache in SVM
  algorithms/kernel/svm/svm_train_thunder_cache.h
Labels: backport-2020, perf

#812 Update names of parameter for SVM
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_test.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/gpu/compute_kernel_dense_dpc_test.cpp
  cpp/oneapi/dal/algo/linear_kernel/common.cpp
  cpp/oneapi/dal/algo/linear_kernel/common.hpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel_test.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc_test.cpp
  cpp/oneapi/dal/algo/svm/backend/interop_model.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/algo/svm/train_types.cpp
  cpp/oneapi/dal/algo/svm/train_types.hpp
  examples/oneapi/cpp/source/linear_kernel/linear_kernel_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/dpc/source/linear_kernel/linear_kernel_dense_batch.cpp
  examples/oneapi/dpc/source/svm/svm_two_class_thunder_dense_batch.cpp
Labels: backport-2021, dpc++

#845 Array: operator[] for mutable data removed
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/array.hpp
Labels: backport-2021

#808 Align of get & return labels for SVM with other classification
  cpp/oneapi/dal/algo/linear_kernel/common.cpp
  cpp/oneapi/dal/algo/linear_kernel/common.hpp
  cpp/oneapi/dal/algo/rbf_kernel/common.cpp
  cpp/oneapi/dal/algo/rbf_kernel/common.hpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel_test.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_kernel_thunder_dpc_test.cpp
  cpp/oneapi/dal/algo/svm/backend/interop_model.hpp
  cpp/oneapi/dal/algo/svm/backend/utils.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/algo/svm/train_types.cpp
  cpp/oneapi/dal/algo/svm/train_types.hpp
  examples/oneapi/cpp/source/svm/svm_two_class_smo_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_two_class_thunder_dense_batch.cpp
  examples/oneapi/dpc/source/svm/svm_two_class_thunder_dense_batch.cpp
Labels: backport-2021, dpc++

#829 Build and run tests using Bazel
  .ci/pipeline/ci.yml
  .gitignore
  cpp/daal/BUILD
  cpp/daal/src/algorithms/low_order_moments/BUILD
  cpp/daal/src/algorithms/normalization/zscore/BUILD
  cpp/oneapi/dal/BUILD
  cpp/oneapi/dal/algo/BUILD
  cpp/oneapi/dal/algo/decision_forest/BUILD
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_train_cls_kernel_test.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_train_reg_kernel_test.cpp
  cpp/oneapi/dal/algo/decision_forest/common_cls_test.cpp
  cpp/oneapi/dal/algo/decision_forest/common_reg_test.cpp
  cpp/oneapi/dal/algo/decision_forest/test/utils.hpp
  cpp/oneapi/dal/algo/jaccard/BUILD
  cpp/oneapi/dal/algo/kmeans/BUILD
  cpp/oneapi/dal/algo/kmeans/backend/cpu/train_kernel_lloyd_dense_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/BUILD
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense_test.cpp
  cpp/oneapi/dal/algo/knn/BUILD
  cpp/oneapi/dal/algo/linear_kernel/BUILD
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_test.cpp
  cpp/oneapi/dal/algo/pca/BUILD
  cpp/oneapi/dal/algo/rbf_kernel/BUILD
  cpp/oneapi/dal/algo/rbf_kernel/backend/cpu/compute_kernel_test.cpp
  cpp/oneapi/dal/algo/svm/BUILD
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel_test.cpp
  cpp/oneapi/dal/graph/BUILD
  cpp/oneapi/dal/io/BUILD
  cpp/oneapi/dal/table/BUILD
  cpp/oneapi/dal/table/column_accessor_test.cpp
  cpp/oneapi/dal/table/homogen_test.cpp
  cpp/oneapi/dal/util/BUILD
  dev/bazel/dal.bzl
  dev/bazel/release.bzl
  examples/oneapi/cpp/BUILD
Labels: backport-2021

#865 Improved csv reader error handling
  cpp/oneapi/dal/io/csv/backend/cpu/read_kernel.cpp
  cpp/oneapi/dal/io/csv/backend/gpu/read_kernel_dpc.cpp
Labels: backport-2021

#836 enabled oneAPI kmeans_init methods
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/to_daal_method.hpp
  cpp/oneapi/dal/algo/kmeans_init/common.hpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops_dpc.cpp
  examples/oneapi/cpp/BUILD
  examples/oneapi/cpp/onedal_lnx.lst
  examples/oneapi/cpp/onedal_mac.lst
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_default_dense.cpp
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_dense.cpp
  examples/oneapi/data/kmeans_init_dense.csv
  examples/oneapi/data/kmeans_init_dense_ground_truth.csv
  examples/oneapi/dpc/onedal_lnx.lst
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_default_dense.cpp
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_dense.cpp
Labels: backport-2021, dpc++, interfaces, new algorithm

#868 enabled oneAPI kmeans_init methods (#836)
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/gpu/compute_kernel_dense_dpc_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/to_daal_method.hpp
  cpp/oneapi/dal/algo/kmeans_init/common.hpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops_dpc.cpp
  examples/oneapi/cpp/BUILD
  examples/oneapi/cpp/onedal_lnx.lst
  examples/oneapi/cpp/onedal_mac.lst
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_default_dense.cpp
  examples/oneapi/cpp/source/kmeans_init/kmeans_init_dense.cpp
  examples/oneapi/data/kmeans_init_dense.csv
  examples/oneapi/data/kmeans_init_dense_ground_truth.csv
  examples/oneapi/dpc/onedal_lnx.lst
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_default_dense.cpp
  examples/oneapi/dpc/source/kmeans_init/kmeans_init_dense.cpp
Labels: dpc++, interfaces, new algorithm

#869 enable public CI for rls branches
  .ci/pipeline/ci.yml
Labels: backport-2020, backport-2021

#790 Fixing CSS style code problems
  docs/doxygen/custom/intel_doxygen.css
Labels: backport-2021

#859 required changes for migration to level zero 1.0
  cpp/daal/include/sycl/internal/daal_level_zero_common.h
  cpp/daal/include/sycl/internal/daal_level_zero_types.h
  cpp/daal/include/sycl/internal/daal_ze_module_helper.h
  cpp/daal/include/sycl/internal/error_handling.h
  cpp/daal/include/sycl/internal/kernel_scheduler_sycl.h
  cpp/daal/include/sycl/internal/math/mkl_blas.h
  cpp/daal/include/sycl/internal/math/mkl_lapack.h
Labels: backport-2021

#767 new README
  README.md
  docs/readme-charts/IDP scikit-learn accelearation compared with stock scikit-learn.png
  docs/readme-charts/Intel oneDAL KMeans strong scaling.png
  docs/readme-charts/intel oneDAL KMeans weak scaling.png
  docs/readme-charts/intel oneDAL Spark samples vs Apache Spark MLlib.png
Labels: docs

#877 changes required for level zero 1.0 enabling. Fix for doxygen
  cpp/daal/include/sycl/internal/daal_level_zero_types.h
Labels: backport-2021
