Repository uxlfoundation/oneDAL, pull requests merged in 2020-05, with the labels that each got.

#575 Fix logreg predict instance for GPU
  algorithms/kernel/logistic_regression/logistic_regression_predict_container.h
  algorithms/kernel/logistic_regression/logistic_regression_predict_dense_default_batch_oneapi_fpt.cpp
  algorithms/kernel/logistic_regression/oneapi/logistic_regression_predict_dense_default_batch_oneapi_impl.i
  algorithms/kernel/logistic_regression/oneapi/logistic_regression_predict_kernel_oneapi.h
Labels: bug, dpc++

#578 Doc readme update
  README.md
Labels: docs

#582 Small refactor & fix bugs for SVM
  algorithms/kernel/dbscan/oneapi/dbscan_dense_default_batch_ucapi_impl.i
  algorithms/kernel/kernel_function/kernel_function_linear_batch_container.h
  algorithms/kernel/kernel_function/oneapi/kernel_function_linear_dense_default_kernel_oneapi.h
  algorithms/kernel/kernel_function/oneapi/kernel_function_linear_dense_default_oneapi_impl.i
  algorithms/kernel/kernel_function/oneapi/kernel_function_rbf_dense_default_kernel_oneapi.h
  algorithms/kernel/kernel_function/oneapi/kernel_function_rbf_dense_default_oneapi_impl.i
  algorithms/kernel/svm/oneapi/svm_train_cache_oneapi.h
  algorithms/kernel/svm/oneapi/svm_train_workset_oneapi.h
  service/kernel/oneapi/partition.cpp
  service/kernel/oneapi/reducer.cpp
Labels: bug

#592 Remove CPU dispatcher from SGD Solver for GPU method
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_default_kernel_oneapi.h
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_kernel_oneapi.h
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_kernel_oneapi_instance.h
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_minibatch_kernel_oneapi.h
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_minibatch_oneapi_impl.i
  algorithms/kernel/optimization_solver/sgd/oneapi/sgd_dense_momentum_kernel_oneapi.h
  algorithms/kernel/optimization_solver/sgd/sgd_batch_container.h
  algorithms/kernel/optimization_solver/sgd/sgd_dense_minibatch_batch_oneapi_fpt.cpp
  algorithms/kernel/svm/oneapi/svm_predict_kernel_oneapi.h
  algorithms/kernel/svm/oneapi/svm_train_cache_oneapi.h
  algorithms/kernel/svm/oneapi/svm_train_result_oneapi.h
  algorithms/kernel/svm/oneapi/svm_train_workset_oneapi.h
Labels: bug, dpc++

#599 KMeans block size optimizations have been implemented.
  algorithms/kernel/kmeans/kmeans_lloyd_batch_impl.i
  algorithms/kernel/kmeans/kmeans_lloyd_distr_step1_impl.i
  algorithms/kernel/kmeans/kmeans_lloyd_helper.h
  algorithms/kernel/kmeans/kmeans_lloyd_impl.i
  algorithms/kernel/kmeans/kmeans_lloyd_postprocessing.h
  service/kernel/service_environment.h
  service/kernel/service_topo.cpp
Labels: perf
