Repository uxlfoundation/oneDAL, pull requests merged in 2021-01, with the labels that each got.

#1368 Fix levelzero include
  cpp/daal/include/services/internal/sycl/error_handling_sycl.h
Labels: bug

#1364 WIP: [DOC] Remove the optimization notice
  docs/doxygen/custom/cpp/opt_notice.txt
  docs/doxygen/custom/java/opt_notice.txt
  docs/doxygen/custom/python/opt_notice.txt
  docs/source/conf.py
  docs/source/daal/algorithms/association_rules/association-rules.rst
  docs/source/daal/algorithms/cholesky/cholesky.rst
  docs/source/daal/algorithms/covariance/computation-batch.rst
  docs/source/daal/algorithms/covariance/computation-distributed.rst
  docs/source/daal/algorithms/covariance/computation-online.rst
  docs/source/daal/algorithms/covariance/correlation-and-variance-covariance-matrices.rst
  docs/source/daal/algorithms/decision_forest/decision-forest.rst
  docs/source/daal/algorithms/distance/correlation.rst
  docs/source/daal/algorithms/distance/cosine.rst
  docs/source/daal/algorithms/distributions/bernoulli.rst
  docs/source/daal/algorithms/em/expectation-maximization.rst
  docs/source/daal/algorithms/implicit_als/implicit-alternating-least-squares.rst
  docs/source/daal/algorithms/kmeans/k-means-clustering.rst
  docs/source/daal/algorithms/moments/computation-batch.rst
  docs/source/daal/algorithms/moments/computation-distributed.rst
  docs/source/daal/algorithms/moments/computation-online.rst
  docs/source/daal/algorithms/naive_bayes/naive-bayes-classifier.rst
  docs/source/daal/algorithms/outlier_detection/multivariate.rst
  docs/source/daal/algorithms/pca/principal-component-analysis.rst
  docs/source/daal/algorithms/qr/qr-decomposition.rst
  docs/source/daal/algorithms/svd/singular-value-decomposition.rst
  docs/source/daal/algorithms/svm/support-vector-machine-classifier.rst
  docs/source/daal/services/extracting-version-information.rst
  docs/source/daal/services/managing-computational-environment.rst
  docs/source/opt-notice.rst
  samples/daal/cpp/arrow/README.md
  samples/daal/cpp/kdb/README.md
  samples/daal/cpp/mpi/README.md
  samples/daal/cpp/mysql/README.md
  samples/daal/java/hadoop/README.md
  samples/daal/java/spark/README.md
  samples/daal/scala/spark/README.md
Labels: docs

#1370 [DOC] Make images in readme non-transparent
  docs/readme-charts/IDP scikit-learn accelearation compared with stock scikit-learn.png
  docs/readme-charts/Intel oneDAL KMeans strong scaling.png
  docs/readme-charts/intel oneDAL KMeans weak scaling.png
  docs/readme-charts/intel oneDAL Spark samples vs Apache Spark MLlib.png
Labels: docs

#1360 Update channel for download python packages
  .ci/pipeline/ci.yml
  .ci/scripts/conformance-scripts/download_tests.sh
  .ci/scripts/conformance-scripts/requirements.txt
  .ci/scripts/conformance-scripts/run_tests.py
  .ci/scripts/conformance_test.sh
Labels: infra

#1353 Update env script to support mksh
  deploy/local/vars_lnx.sh
  deploy/local/vars_mac.sh
Labels: infra

#1377 [DOC] Updated README
  README.md
Labels: docs

#1367 host_homogen_table_adapter implementation
  cpp/daal/include/data_management/data/numeric_table.h
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_cls_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/infer_kernel_reg_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_cls_dense.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/train_kernel_reg_dense.cpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/kmeans/backend/cpu/train_kernel_lloyd_dense.cpp
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/infer_kernel_kd_tree_classification.cpp
  cpp/oneapi/dal/algo/knn/backend/cpu/train_kernel_kd_tree_classification.cpp
  cpp/oneapi/dal/algo/linear_kernel/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/common_test.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_svd.cpp
  cpp/oneapi/dal/algo/rbf_kernel/backend/cpu/compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_kernel.cpp
  cpp/oneapi/dal/backend/interop/daal_object_owner.hpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
  cpp/oneapi/dal/detail/common.cpp
  cpp/oneapi/dal/detail/common.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/table/backend/interop/block_info.hpp
  cpp/oneapi/dal/table/backend/interop/host_homogen_table_adapter.cpp
  cpp/oneapi/dal/table/backend/interop/host_homogen_table_adapter.hpp
Labels: oneAPI, perf

#1381 [DOC] Fixed broken links and product names
  cpp/oneapi/dal/algo/decision_forest/common.hpp
  cpp/oneapi/dal/algo/knn/common.hpp
  cpp/oneapi/dal/algo/svm/common.hpp
  docs/source/onedal/get-started/build-and-run-examples.rst
  docs/source/onedal/get-started/prerequisites.rst
Labels: docs

#1384 Add support section to README
  README.md
Labels: docs

#1388 Extend mergify
  .mergify.yml
Labels: infra

#1394 [DOC] Remove FAQ.md
  FAQ.md
Labels: docs

#1371 Host allocations through MKL routines
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/detail/common.hpp
  cpp/oneapi/dal/detail/common_dpc.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/detail/memory_impl_dpc.cpp
  cpp/oneapi/dal/detail/memory_impl_dpc.hpp
  cpp/oneapi/dal/detail/memory_impl_host.cpp
  cpp/oneapi/dal/detail/memory_impl_host.hpp
  cpp/oneapi/dal/table/common.hpp
  cpp/oneapi/dal/table/detail/table_builder.hpp
  cpp/oneapi/dal/table/homogen.hpp
Labels: enhancement, oneAPI
