Repository uxlfoundation/oneDAL, pull requests merged in 2021-05, with the labels that each got.

#1579 Fix down pow2 function
  cpp/oneapi/dal/backend/common.hpp
Labels: bug

#1569 Fix perf in linear models with SOA tables
  cpp/daal/src/algorithms/linear_model/linear_model_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_predict_kernel.h
Labels: perf

#1605 Fix passed build daal4py when there are failed
  .ci/pipeline/ci.yml
Labels: infra

#1593 Model serialization prototype
  cpp/oneapi/dal/algo/svm/backend/model_impl.hpp
  cpp/oneapi/dal/algo/svm/backend/model_interop.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/infer_types.cpp
  cpp/oneapi/dal/algo/svm/infer_types.hpp
  cpp/oneapi/dal/algo/svm/test/serialization.cpp
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/backend/interop/archive.hpp
  cpp/oneapi/dal/backend/serialization.hpp
  cpp/oneapi/dal/detail/archives.hpp
  cpp/oneapi/dal/detail/array_impl.cpp
  cpp/oneapi/dal/detail/array_impl.hpp
  cpp/oneapi/dal/detail/common.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/detail/hash_map.hpp
  cpp/oneapi/dal/detail/paged_vector.hpp
  cpp/oneapi/dal/detail/serialization.cpp
  cpp/oneapi/dal/detail/serialization.hpp
  cpp/oneapi/dal/table/BUILD
  cpp/oneapi/dal/table/backend/empty_table_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.hpp
  cpp/oneapi/dal/table/backend/register_serializable.cpp
  cpp/oneapi/dal/table/common.cpp
  cpp/oneapi/dal/table/common.hpp
  cpp/oneapi/dal/table/detail/table_iface.hpp
  cpp/oneapi/dal/table/homogen.cpp
  cpp/oneapi/dal/table/homogen.hpp
  cpp/oneapi/dal/table/test/common_serialization.cpp
  cpp/oneapi/dal/table/test/homogen_serialization.cpp
  cpp/oneapi/dal/test/archives.cpp
  cpp/oneapi/dal/test/array_serialization.cpp
  cpp/oneapi/dal/test/engine/linalg/random.hpp
  cpp/oneapi/dal/test/engine/mocks.hpp
  cpp/oneapi/dal/test/engine/serialization.hpp
  cpp/oneapi/dal/test/engine/tables.hpp
  cpp/oneapi/dal/test/hash_map.cpp
  cpp/oneapi/dal/test/paged_vector.cpp
  cpp/oneapi/dal/test/serialization.cpp
Labels: oneAPI

#1592 nuSVM
  cpp/daal/src/algorithms/svm/svm_train_boser_impl.i
  cpp/daal/src/algorithms/svm/svm_train_common.h
  cpp/daal/src/algorithms/svm/svm_train_common_avx512_impl.i
  cpp/daal/src/algorithms/svm/svm_train_common_impl.i
  cpp/daal/src/algorithms/svm/svm_train_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_workset.h
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_cls_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_reg_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_cls_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_reg_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_cls_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_reg_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_cls_kernel_smo_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_cls_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_reg_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/model_impl.hpp
  cpp/oneapi/dal/algo/svm/common.cpp
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.cpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops_dpc.cpp
  cpp/oneapi/dal/algo/svm/infer_types.cpp
  cpp/oneapi/dal/algo/svm/test/badargs.cpp
  cpp/oneapi/dal/algo/svm/test/serialization.cpp
  cpp/oneapi/dal/algo/svm/train_types.cpp
  cpp/oneapi/dal/backend/serialization.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  examples/oneapi/cpp/onedal_lnx.lst
  examples/oneapi/cpp/onedal_mac.lst
  examples/oneapi/cpp/source/svm/svm_nu_cls_thunder_dense_batch.cpp
  examples/oneapi/cpp/source/svm/svm_nu_reg_thunder_dense_batch.cpp
Labels: interfaces, new algorithm

#1624 Reduce block size for compute gradient in SVM
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
Labels: perf

#1623 Dev/agorshk csr table2
  cpp/oneapi/dal/backend/interop/csr_block_owner.hpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/table/BUILD
  cpp/oneapi/dal/table/backend/common_kernels.hpp
  cpp/oneapi/dal/table/backend/csr_kernels.cpp
  cpp/oneapi/dal/table/backend/csr_kernels.hpp
  cpp/oneapi/dal/table/backend/csr_table_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_kernels.cpp
  cpp/oneapi/dal/table/backend/homogen_kernels.hpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.hpp
  cpp/oneapi/dal/table/backend/interop/host_csr_table_adapter.cpp
  cpp/oneapi/dal/table/backend/interop/host_csr_table_adapter.hpp
  cpp/oneapi/dal/table/detail/csr.cpp
  cpp/oneapi/dal/table/detail/csr.hpp
  cpp/oneapi/dal/table/detail/csr_access_iface.hpp
  cpp/oneapi/dal/table/detail/csr_accessor.hpp
  cpp/oneapi/dal/table/detail/csr_block.hpp
  cpp/oneapi/dal/table/detail/table_iface.hpp
  cpp/oneapi/dal/table/detail/test/csr_accessor.cpp
Labels: oneAPI

#1634 add check in traversing
  cpp/daal/src/algorithms/dtrees/gbt/gbt_model.cpp
Labels: bug

#1632 Workaround roc_auc from hanging
  cpp/daal/src/data_management/roc_auc_score.cpp
Labels: bug

#1590 Enable sparse support for SVM's for oneAPI interfaces
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial.cpp
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial_csr_fast_impl.i
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_types_polynomial.h
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_cls_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/infer_reg_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_cls_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_reg_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_cls_kernel_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_cls_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/backend/kernel_function_impl.hpp
  cpp/oneapi/dal/algo/svm/backend/model_conversion.hpp
  cpp/oneapi/dal/algo/svm/detail/kernel_function.cpp
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
  cpp/oneapi/dal/table/backend/csr_kernels.cpp
  cpp/oneapi/dal/table/detail/csr.cpp
  cpp/oneapi/dal/table/detail/csr.hpp
Labels: oneAPI

#1635 Enable MD flag for windows
  dev/make/cmplr.dpcpp.mk
  dev/make/cmplr.icc.mk
  dev/make/cmplr.vc.mk
  examples/daal/cpp/CMakeLists.txt
  examples/daal/cpp/daal_win.vcxproj.tpl
  examples/daal/cpp/makefile_win
  examples/daal/cpp_sycl/CMakeLists.txt
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/makefile_win
  examples/oneapi/cpp/CMakeLists.txt
  examples/oneapi/cpp/makefile_win
  examples/oneapi/cpp/onedal_win.vcxproj.tpl
  examples/oneapi/dpc/CMakeLists.txt
  examples/oneapi/dpc/makefile_win
  examples/oneapi/dpc/onedal_win.vcxproj.tpl
  makefile
  samples/daal/cpp/arrow/launcher.bat
  samples/daal/cpp/kdb/launcher.bat
  samples/daal/cpp/mpi/launcher.bat
  samples/daal/cpp/mysql/launcher.bat
Labels: infra

#1644 Fix of nd_range usage in covariance kernel
  cpp/oneapi/dal/backend/primitives/stat/cov_dpc.cpp
Labels: bug

#1643 SVM gpu: check on multiclass in infer kernel
  cpp/oneapi/dal/algo/svm/backend/gpu/infer_cls_kernel_dpc.cpp
Labels: bug

#1648 Fix bugs with multiclass model
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_svm_model.h
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_impl.i
  cpp/daal/src/algorithms/multiclassclassifier/multiclassclassifier_train_oneagainstone_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/oneapi/dal/algo/svm/backend/cpu/train_cls_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/cpu/train_reg_kernel.cpp
  cpp/oneapi/dal/algo/svm/backend/gpu/train_cls_kernel_thunder_dpc.cpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/backend/interop/csr_block_owner.hpp
Labels: bug

#1645 Fix backward compatibility in data management
  cpp/oneapi/dal/algo/svm/infer_types.cpp
  cpp/oneapi/dal/algo/svm/infer_types.hpp
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/detail/array_compat.hpp
  cpp/oneapi/dal/detail/array_impl.cpp
  cpp/oneapi/dal/detail/array_impl.hpp
  cpp/oneapi/dal/detail/array_utils.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/table/backend/accessor_compat.hpp
  cpp/oneapi/dal/table/backend/csr_table_impl.hpp
  cpp/oneapi/dal/table/backend/empty_table_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_table_builder_impl.hpp
  cpp/oneapi/dal/table/backend/homogen_table_impl.hpp
  cpp/oneapi/dal/table/column_accessor.hpp
  cpp/oneapi/dal/table/common.cpp
  cpp/oneapi/dal/table/common.hpp
  cpp/oneapi/dal/table/detail/access_iface_compat.hpp
  cpp/oneapi/dal/table/detail/columns_access_iface.hpp
  cpp/oneapi/dal/table/detail/csr.cpp
  cpp/oneapi/dal/table/detail/csr.hpp
  cpp/oneapi/dal/table/detail/csr_access_iface.hpp
  cpp/oneapi/dal/table/detail/csr_accessor.hpp
  cpp/oneapi/dal/table/detail/csr_block.hpp
  cpp/oneapi/dal/table/detail/homogen_utils.hpp
  cpp/oneapi/dal/table/detail/rows_access_iface.hpp
  cpp/oneapi/dal/table/detail/table_builder.hpp
  cpp/oneapi/dal/table/detail/table_iface.hpp
  cpp/oneapi/dal/table/detail/table_utils.cpp
  cpp/oneapi/dal/table/detail/table_utils.hpp
  cpp/oneapi/dal/table/homogen.cpp
  cpp/oneapi/dal/table/homogen.hpp
  cpp/oneapi/dal/table/row_accessor.hpp
  cpp/oneapi/dal/test/engine/mocks.hpp
  docs/source/conf.py
Labels: bug, oneAPI

#1639 NuSVM Fixes
  cpp/daal/src/algorithms/svm/svm_train_common_avx512_impl.i
  cpp/daal/src/algorithms/svm/svm_train_kernel.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_kernel.h
  cpp/oneapi/dal/algo/svm/backend/model_impl.hpp
  examples/oneapi/cpp/source/svm/svm_nu_reg_thunder_dense_batch.cpp
Labels: bug
