Repository uxlfoundation/oneDAL, pull requests merged in 2021-06, with the labels that each got.

#1647 Enable MDd flag for windows
  cpp/daal/src/externals/core_threading_win_dll.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_naive_local_dpc.cpp
  dev/make/cmplr.dpcpp.mk
  dev/make/cmplr.icc.mk
  dev/make/cmplr.vc.mk
  examples/daal/cpp/CMakeLists.txt
  examples/daal/cpp/daal_win.sln.tpl
  examples/daal/cpp/daal_win.vcxproj.tpl
  examples/daal/cpp/daal_win.vcxproj.user.tpl
  examples/daal/cpp_sycl/CMakeLists.txt
  examples/daal/cpp_sycl/daal_win.sln.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.tpl
  examples/daal/cpp_sycl/daal_win.vcxproj.user.tpl
  examples/oneapi/cpp/CMakeLists.txt
  examples/oneapi/cpp/onedal_win.sln.tpl
  examples/oneapi/cpp/onedal_win.vcxproj.tpl
  examples/oneapi/cpp/onedal_win.vcxproj.user.tpl
  examples/oneapi/dpc/CMakeLists.txt
  examples/oneapi/dpc/onedal_win.sln.tpl
  examples/oneapi/dpc/onedal_win.vcxproj.tpl
  makefile
Labels: enhancement, infra

#1675 SSSP bad arg fix
  cpp/oneapi/dal/algo/shortest_paths/backend/cpu/traverse_default_kernel.hpp
  cpp/oneapi/dal/algo/shortest_paths/common.cpp
  cpp/oneapi/dal/algo/shortest_paths/common.hpp
  cpp/oneapi/dal/algo/shortest_paths/detail/traverse_ops.hpp
  cpp/oneapi/dal/algo/subgraph_isomorphism/backend/cpu/matching.hpp
  cpp/oneapi/dal/backend/memory.hpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
  cpp/oneapi/dal/graph/detail/directed_adjacency_vector_graph_builder.hpp
Labels: backport-2021

#1679 NuSVM Docs
  cpp/oneapi/dal/algo/svm/common.hpp
  cpp/oneapi/dal/algo/svm/infer_types.hpp
  cpp/oneapi/dal/algo/svm/train_types.hpp
  docs/README.md
  docs/source/includes/svm/svm-examples.rst
  docs/source/onedal/algorithms/svm/svm.rst
  docs/source/onedal/glossary.rst
Labels: docs

#1556 DPC++train and infer kernels for K-Means
  cpp/oneapi/dal/algo/kmeans/BUILD
  cpp/oneapi/dal/algo/kmeans/backend/gpu/cluster_updater.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_defines.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl_dbl_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_fp_impl_flt_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_integral.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_integral_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/test/batch_impl_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/test/perf_batch_impl_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_dense_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/common.cpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
  cpp/oneapi/dal/algo/kmeans/test/badarg.cpp
  cpp/oneapi/dal/algo/kmeans/test/batch.cpp
  cpp/oneapi/dal/backend/common.hpp
  cpp/oneapi/dal/backend/primitives/distance/squared_l2_distance_misc_dpc.cpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
Labels: dpc++

#1708 Safe environment finalization
  cpp/daal/src/externals/core_threading_win_dll.cpp
Labels: bug

#1723 Fix error handling in data archives
  cpp/daal/include/data_management/data/data_archive.h
Labels: bug

#1724 Add new perf data for scikit-learn-intelex
  README.md
  docs/readme-charts/scikit-learn-acceleration-2021.2.3.png
Labels: docs

#1713 OneAPI tests for K-Means initialization
  cpp/oneapi/dal/algo/kmeans_init/BUILD
  cpp/oneapi/dal/algo/kmeans_init/backend/cpu/compute_kernel_dense_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/common_kmeans_init_test.cpp
  cpp/oneapi/dal/algo/kmeans_init/test/badarg.cpp
  cpp/oneapi/dal/algo/kmeans_init/test/batch.cpp
Labels: oneAPI

#1696 Add security md file
  SECURITY.md
Labels: docs

#1734 Fix building with custom instruction set
  cpp/daal/include/services/internal/daal_kernel_defines.h
  cpp/daal/src/algorithms/kernel.h
  cpp/oneapi/dal/backend/dispatcher.hpp
Labels: bug
