Repository uxlfoundation/oneDAL, pull requests merged in 2022-02, with the labels that each got.

#2069 Changed bazel binary call
  .ci/pipeline/ci.yml
Labels: bug, infra

#2062 Fix dpcpp ext::oneapi deprecations in new compiler versions
  cpp/oneapi/dal/algo/dbscan/backend/gpu/kernel_fp_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_service_kernels_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_integral_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/functors.hpp
Labels: dpc++

#2077 Fix bugs in RandomForest
  cpp/daal/src/algorithms/dtrees/forest/df_train_dense_default_impl.i
Labels: bug
