Repository uxlfoundation/oneDAL, pull requests merged in 2023-11, with the labels that each got.

#2562 Fix 'no type named 'uint32_t'' failure in ICX build
  cpp/daal/include/algorithms/algorithm_types.h
  cpp/daal/src/algorithms/algorithm_hyperparameter.cpp
  cpp/daal/src/algorithms/covariance/covariance_hyperparameter.cpp
  cpp/daal/src/algorithms/covariance/covariance_hyperparameter_impl.h
  cpp/daal/src/algorithms/covariance/covariance_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter.cpp
  cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter_impl.h
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
  cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter.cpp
  cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter_impl.h
Labels: bug

#2575 coverity fixes 2024.0.1
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_model_impl.h
  cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_model_impl.h
Labels: bug

#2560 [bug] Fix oneDALConfig.cmake.in for daal examples using a daal-only build
  cmake/templates/oneDALConfig.cmake.in
Labels: bug

#2571 Implement copy constructor for csr_table class
  cpp/oneapi/dal/table/csr.cpp
  cpp/oneapi/dal/table/csr.hpp
  cpp/oneapi/dal/table/detail/table_utils.cpp
  cpp/oneapi/dal/table/detail/table_utils.hpp
  cpp/oneapi/dal/table/test/csr.cpp
Labels: bug, testing

#2563 Update TPP file according to the recent changes
  third-party-programs.txt
Labels: docs

#2585 Monthly doc package updates
  .github/renovate.json
Labels: docs, dependencies

#2548 Basic statistics algorithm for sparse data
  cpp/oneapi/dal/algo/basic_statistics/backend/cpu/compute_kernel.cpp
  cpp/oneapi/dal/algo/basic_statistics/backend/cpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel.hpp
  cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel_csr_impl.hpp
  cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel_csr_impl_dpc.cpp
  cpp/oneapi/dal/algo/basic_statistics/backend/gpu/compute_kernel_sparse_dpc.cpp
  cpp/oneapi/dal/algo/basic_statistics/common.hpp
  cpp/oneapi/dal/algo/basic_statistics/compute_types.cpp
  cpp/oneapi/dal/algo/basic_statistics/detail/compute_ops.cpp
  cpp/oneapi/dal/algo/basic_statistics/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/basic_statistics/detail/compute_ops_dpc.cpp
  cpp/oneapi/dal/algo/basic_statistics/test/batch.cpp
  cpp/oneapi/dal/algo/basic_statistics/test/fixture.hpp
  cpp/oneapi/dal/test/engine/BUILD
  cpp/oneapi/dal/test/engine/csr_table_builder.hpp
Labels: enhancement

#2597 Update Notices and Disclaimers
  docs/source/conf.py
  docs/source/index-toc.rst
  docs/source/legal.rst
Labels: docs

#2547 feature: dbscan optimizations
  cpp/oneapi/dal/algo/dbscan/backend/gpu/compute_kernel_brute_force_dpc.cpp
  cpp/oneapi/dal/algo/dbscan/backend/gpu/kernel_fp_impl.hpp
Labels: perf
