Repository uxlfoundation/oneDAL, pull requests merged in 2023-06, with the labels that each got.

#2391 GBT inference optimization
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/dtrees/gbt/gbt_predict_dense_default_impl.i
  cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_predict_dense_default_batch_impl.i
Labels: perf

#2371 Bazel version update to 6.2
  .bazelversion
  .ci/pipeline/ci.yml
  WORKSPACE
  cpp/oneapi/dal/algo/louvain/test/louvain_test.cpp
  cpp/oneapi/dal/table/BUILD
  cpp/oneapi/dal/table/test/column_accessor.cpp
  cpp/oneapi/dal/table/test/common.cpp
  cpp/oneapi/dal/test/engine/BUILD
  cpp/oneapi/dal/test/engine/gtest_main.cpp
  dev/bazel/cc.bzl
  dev/bazel/dal.bzl
  third-party-programs.txt
Labels: infra, testing, dependencies

#2425 [doc]Update conf.py
  docs/source/conf.py
Labels: docs
