Repository uxlfoundation/oneDAL, pull requests merged in 2023-12, with the labels that each got.

#2464 Random Forest GPU kernel update
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/infer_kernel_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_feature_type_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_cls_hist_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_reg_hist_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_misc_structs.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_node_helpers.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_node_helpers.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_helpers.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_sp_opt_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_splitter_sp_opt_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/test/spmd.cpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
Labels: bug, enhancement, perf

#2616 Add initial implementation for detail::csr_table_builder
  cpp/oneapi/dal/table/BUILD
  cpp/oneapi/dal/table/backend/csr_table_builder_impl.hpp
  cpp/oneapi/dal/table/detail/table_builder.cpp
  cpp/oneapi/dal/table/detail/table_builder.hpp
  cpp/oneapi/dal/table/detail/table_iface.hpp
  cpp/oneapi/dal/table/detail/test/csr_utils.cpp
Labels: enhancement, testing

#2558 Distributed kNN scalability and optimizations
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc.hpp
  cpp/oneapi/dal/algo/knn/backend/gpu/infer_kernel_impl_dpc_distr.hpp
  cpp/oneapi/dal/backend/primitives/search/search_dpc.cpp
  cpp/oneapi/dal/backend/primitives/selection/select_indexed_dpc.cpp
  cpp/oneapi/dal/backend/primitives/split_table.hpp
Labels: enhancement, perf
