Repository uxlfoundation/oneDAL, pull requests merged in 2024-04, with the labels that each got.

#2705 [bug] Add signflip to CPU online PCA
  cpp/daal/src/algorithms/pca/pca_dense_correlation_online_kernel.h
  cpp/oneapi/dal/algo/pca/backend/cpu/finalize_train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/test/fixture.hpp
  cpp/oneapi/dal/algo/pca/test/online.cpp
Labels: bug

#2699 Update oneAPI DPC++ compiler and micromkl GPU versions
  .ci/env/apt.sh
  WORKSPACE
  dev/download_micromkl.bat
  dev/download_micromkl.sh
Labels: infra

#2745 Workaround to sparse primitives failures in private CI
  cpp/oneapi/dal/backend/primitives/sparse_blas/test/gemm_dpc.cpp
  cpp/oneapi/dal/backend/primitives/sparse_blas/test/gemv_dpc.cpp
Labels: testing

#2750 [bug] Fix event dependencies for PCA infer on GPU
  cpp/oneapi/dal/algo/pca/backend/gpu/infer_kernel_dpc.cpp
Labels: bug

#2701 Fix a misprint for Sphinx generator
  docs/source/daal/algorithms/quality_metrics/default/for-multi-class-classification.rst
Labels: docs
