Repository uxlfoundation/oneDAL, pull requests merged in 2024-05, with the labels that each got.

#2753 chore: add OpenSSF Scorecard GitHub Action
  .github/workflows/openssf-scorecard.yml
  README.md
Labels: enhancement

#2670 [enh] add functors for infinite and NaN checking in DAL
  cpp/oneapi/dal/backend/primitives/reduction/functors.hpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_1d_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_atomic_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_blocking_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_naive_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_naive_local_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_wrapper_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_blocking_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_narrow_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_wide_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_wrapper_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_1d_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_random_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_uniform_dpc.cpp
Labels: enhancement, dpc++

#2766 Fix coverity 'invalid iterator' failure
  cpp/oneapi/dal/detail/cpu_info_impl.cpp
Labels: bug

#2794 Improve SYCL kernels in CSR table
  cpp/oneapi/dal/table/backend/csr_kernels.cpp
Labels: dpc++

#2804 Update requests version
  docs/requirements.txt
Labels: docs, dependencies
