Repository uxlfoundation/oneDAL, pull requests merged in 2024-01, with the labels that each got.

#2583 feature: adding blocking in reduction primitives
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_blocking_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_dpc.hpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_naive_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_wrapper_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_blocking_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_dpc.hpp
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_rw_wrapper_dpc.cpp
Labels: enhancement, dpc++

#2629 Add GPU support in detail::csr_table_builder class
  cpp/oneapi/dal/table/backend/csr_table_builder_impl.hpp
  cpp/oneapi/dal/table/detail/table_builder.hpp
  cpp/oneapi/dal/table/detail/table_iface.hpp
  cpp/oneapi/dal/table/detail/test/csr_utils.cpp
Labels: enhancement, dpc++, testing

#2626 fix: bazel heterogen serialization
  cpp/oneapi/dal/table/backend/heterogen_kernels.cpp
  cpp/oneapi/dal/table/test/heterogen_serialization.cpp
Labels: bug

#2641 chore(workflows): add read permissions for actions
  .github/workflows/docker-validation-ci.yml
  .github/workflows/docker-validation-nightly.yml
  .github/workflows/renovate-validation.yml
Labels: infra

#2618 feature: adding svd(GPU) support + removing code duplications in Cov/PcaCov
  cpp/oneapi/dal/algo/covariance/backend/gpu/compute_kernel_dense_impl_dpc.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/finalize_compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/misc.hpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/partial_compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/finalize_train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/finalize_train_kernel_svd.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/partial_train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/partial_train_kernel_svd.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_cov.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_precomputed.cpp
  cpp/oneapi/dal/algo/pca/backend/cpu/train_kernel_svd.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/finalize_train_kernel_cov_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/finalize_train_kernel_svd_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/misc.hpp
  cpp/oneapi/dal/algo/pca/backend/gpu/partial_train_kernel_cov_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_cov_impl_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_precomputed_impl_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_svd_dpc.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_svd_impl.hpp
  cpp/oneapi/dal/algo/pca/backend/gpu/train_kernel_svd_impl_dpc.cpp
  cpp/oneapi/dal/algo/pca/test/badarg.cpp
  cpp/oneapi/dal/algo/pca/test/batch.cpp
  cpp/oneapi/dal/algo/pca/test/overflow.cpp
  cpp/oneapi/dal/algo/pca/test/serialization.cpp
  cpp/oneapi/dal/backend/primitives/lapack.hpp
  cpp/oneapi/dal/backend/primitives/lapack/BUILD
  cpp/oneapi/dal/backend/primitives/lapack/gesvd.hpp
  cpp/oneapi/dal/backend/primitives/lapack/gesvd_dpc.cpp
  cpp/oneapi/dal/backend/primitives/lapack/misc.hpp
  cpp/oneapi/dal/backend/primitives/stat/cov.hpp
  cpp/oneapi/dal/backend/primitives/stat/cov_dpc.cpp
  cpp/oneapi/dal/backend/primitives/stat/test/cov_dpc.cpp
  examples/oneapi/dpc/source/pca/pca_svd_dense_batch.cpp
Labels: new algorithm, perf

#2647 [enh] remove common.mk unused defined commands
  dev/make/common.mk
Labels: enhancement

#2642 Align Newton-CG and CG-solver stopping conditions with sklearn.utils
  cpp/oneapi/dal/algo/logistic_regression/detail/optimizer.cpp
  cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/cg_solver.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/cg_solver_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/common.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/common_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/line_search.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/newton_cg.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/cg_solver_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
Labels: enhancement

#2631 fix: replace deprecated `sycl::abs` to `sycl::fabs`
  cpp/oneapi/dal/algo/objective_function/backend/gpu/compute_kernel_dense_batch_impl_dpc.cpp
  cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
Labels: dpc++, oneAPI
