Repository uxlfoundation/oneDAL, pull requests merged in 2024-12, with the labels that each got.

#2990 [CI] prepare for ownership change for Nightly-build
  .github/workflows/nightly-build.yml
Labels: infra

#2996 MAINT: Delete unused operators for profiler class
  cpp/oneapi/dal/detail/profiler.hpp
Labels: enhancement

#2998 MAINT: Delete unused operators for scoped lock class
  cpp/oneapi/dal/detail/threading.hpp
Labels: enhancement

#2995 MAINT: Add default constructor for global policy context
  cpp/oneapi/dal/detail/global_context.hpp
Labels: enhancement

#3006 Fix coverity hits in boosting algorithms
  cpp/daal/include/algorithms/boosting/adaboost_predict_types.h
  cpp/daal/include/algorithms/boosting/brownboost_predict_types.h
  cpp/daal/include/algorithms/boosting/logitboost_predict_types.h
Labels: enhancement

#3003 DOC: Update doc and internal links after uxl transfer
  .ci/env/tbb.bat
  .ci/env/tbb.sh
  .ci/pipeline/ci.yml
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/docker-validation-nightly.yml
  .github/workflows/label-enforcement.yml
  .github/workflows/openssf-scorecard.yml
  CONTRIBUTING.md
  INSTALL.md
  MAINTAINERS.md
  README.md
  SECURITY.md
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
  cpp/daal/src/threading/threading.h
  deploy/nuget/inteldal.nuspec.tpl
  dev/download_tbb.sh
  docs/README.md
  docs/source/404.rst
  docs/source/conf.py
  docs/source/contribution/coding_guide.rst
  docs/source/contribution/cpu_features.rst
  docs/source/contribution/threading.rst
  docs/source/daal-interfaces.rst
  docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
  docs/source/installation.rst
  docs/source/substitutions_specific.txt
Labels: docs

#2997 MAINT: Delete unused operators for spmatrix handle class
  cpp/oneapi/dal/detail/sparse_matrix_handle_impl.hpp
Labels: enhancement

#3010 feat: add `gcov` code coverage support
  dev/make/compiler_definitions/dpcpp.mk
  dev/make/compiler_definitions/icx.mkl.32e.mk
  makefile
Labels: enhancement

#2950 [CI] use sklearnex azure pipelines template for sklearnex CI step
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  .ci/scripts/conformance-scripts/algorithms.txt
  .ci/scripts/conformance-scripts/download_tests.sh
  .ci/scripts/conformance-scripts/run_tests.py
  .ci/scripts/conformance-scripts/run_tests_with_context.py
  .ci/scripts/conformance-scripts/run_xpu_conformance.py
  .ci/scripts/conformance-scripts/utils.py
  .ci/scripts/conformance_test.sh
Labels: infra

#2988 fix: array coverity hits
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/chunked_array.hpp
  cpp/oneapi/dal/detail/chunked_array_impl.cpp
  cpp/oneapi/dal/detail/chunked_array_impl.hpp
Labels: infra

#2966 fix: avoid additional array allocation in host to device transfer
  cpp/oneapi/dal/backend/memory.hpp
Labels: bug

#3012 Fix illegal instructions failures in examples
  cpp/daal/include/algorithms/algorithm_container_base.h
  cpp/daal/include/algorithms/algorithm_container_base_batch.h
  cpp/daal/include/algorithms/boosting/adaboost_predict_types.h
  cpp/daal/include/algorithms/boosting/brownboost_predict_types.h
  cpp/daal/include/algorithms/boosting/logitboost_predict_types.h
  cpp/daal/src/algorithms/adaboost/adaboost_predict_batch.cpp
  cpp/daal/src/algorithms/algorithm_base_impl.cpp
  cpp/daal/src/algorithms/brownboost/brownboost_predict_batch.cpp
  cpp/daal/src/algorithms/logitboost/logitboost_predict_batch.cpp
Labels: bug

#3019 docs: update build status badge link in `README.md`
  README.md
Labels: docs

#3015 Update openblas.sh
  .ci/env/openblas.sh
Labels: dependencies

#2839 chore(workflows): pin GitHub Actions by hash
  .github/workflows/docker-validation-ci.yml
  .github/workflows/docker-validation-nightly.yml
  .github/workflows/nightly-build.yml
  .github/workflows/pr-checklist.yml
  .github/workflows/renovate-validation.yml
Labels: enhancement

#3016 DOC: Instructions for installing with dependencies from `conda`
  INSTALL.md
Labels: docs

#3024 Disable LinuxMakeGNU_OpenBLAS_x86 step in CI
  .ci/pipeline/ci.yml
Labels: infra

#3023 test: remove outdated todos in tests
  cpp/oneapi/dal/backend/primitives/blas/test/gemv_dpc.cpp
  cpp/oneapi/dal/backend/primitives/selection/test/select_flagged_dpc.cpp
  cpp/oneapi/dal/backend/primitives/selection/test/select_indexed_rows_dpc.cpp
Labels: testing

#3022 Fix Coverity hits for covariance, correlation and cosine distances
  cpp/daal/include/algorithms/covariance/covariance_batch.h
  cpp/daal/include/algorithms/covariance/covariance_online.h
  cpp/daal/include/algorithms/covariance/covariance_types.h
  cpp/daal/include/algorithms/distance/correlation_distance.h
  cpp/daal/include/algorithms/distance/cosine_distance.h
  cpp/daal/src/algorithms/covariance/covariance_input.cpp
  cpp/daal/src/algorithms/covariance/covariance_online_parameter.cpp
  cpp/daal/src/algorithms/covariance/covariance_step2_distr_input.cpp
Labels: enhancement
