Repository uxlfoundation/oneDAL, pull requests merged in 2024-08, with the labels that each got.

#2849 chore(workflows): add `editorconfig-checker`
  .ci/env/editorconfig-checker.sh
  .ci/pipeline/ci.yml
  .ecrc
  .editorconfig
  .github/renovate.json
  CONTRIBUTING.md
Labels: enhancement, infra

#2850 Set means to zero in online covariance GPU if assume_centered=True
  cpp/oneapi/dal/algo/covariance/backend/gpu/finalize_compute_kernel_dense_impl_dpc.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/partial_compute_kernel_dense_dpc.cpp
  cpp/oneapi/dal/algo/covariance/test/batch.cpp
  cpp/oneapi/dal/algo/covariance/test/compute_parameters.cpp
  cpp/oneapi/dal/algo/covariance/test/fixture.hpp
  cpp/oneapi/dal/algo/covariance/test/online.cpp
  cpp/oneapi/dal/algo/covariance/test/online_spmd.cpp
  cpp/oneapi/dal/algo/covariance/test/spmd.cpp
Labels: bug, testing

#2882 [fix] Fix online SPMD algorithms finalize call
  cpp/oneapi/dal/algo/basic_statistics/backend/gpu/finalize_compute_kernel_dense_impl_dpc.cpp
  cpp/oneapi/dal/algo/basic_statistics/test/online_spmd.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/finalize_compute_kernel_dense_impl_dpc.cpp
  cpp/oneapi/dal/algo/covariance/test/online_spmd.cpp
  cpp/oneapi/dal/algo/linear_regression/backend/gpu/finalize_train_kernel_norm_eq_impl_dpc.cpp
  cpp/oneapi/dal/algo/linear_regression/test/online_spmd.cpp
  cpp/oneapi/dal/algo/pca/backend/gpu/finalize_train_kernel_cov_impl_dpc.cpp
  cpp/oneapi/dal/algo/pca/test/online_spmd.cpp
Labels: bug

#2885 [enhancement] Add a label checker to GitHub Actions
  .github/workflows/label-enforcement.yml
Labels: infra
