Repository uxlfoundation/oneDAL, pull requests merged in 2024-09, with the labels that each got.

#2887 [bug] fix nightly-build regression caused by #2712
  .github/workflows/nightly-build.yml
Labels: infra

#2888 fix: add new DAAL_EXPORT macros for ICX support
  cpp/daal/src/algorithms/implicit_als/implicit_als_predict_ratings_result_fpt.cpp
  cpp/daal/src/algorithms/linear_model/linear_model_predict_batch_fpt.cpp
  cpp/daal/src/algorithms/normalization/minmax/minmax_fpt.cpp
  cpp/daal/src/algorithms/pca/pca_result_fpt.cpp
  cpp/daal/src/algorithms/pca/transform/pca_transform_batch_fpt.cpp
  cpp/daal/src/algorithms/svd/svd_dense_default_batch_fpt.cpp
  cpp/daal/src/algorithms/svd/svd_dense_default_online_fpt.cpp
Labels: bug

#2889 Update to 2025.0.0 version
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#2891 CI: Add more qemu versions
  .ci/env/apt.sh
Labels: testing

#2635 feat: SHAP values for binary classification [target: r2025.0]
  cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_predict.h
  cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_predict_types.h
  cpp/daal/include/services/error_indexes.h
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_container.h
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_kernel.h
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_result_fpt.cpp
  cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_predict_types.cpp
  cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_predict_dense_default_batch_impl.i
  cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_predict_types.cpp
  cpp/daal/src/algorithms/dtrees/gbt/treeshap.h
  cpp/daal/src/services/error_handling.cpp
  examples/daal/cpp/source/gradient_boosted_trees/gbt_cls_traversed_model_builder.cpp
Labels: enhancement, API breaking change

#2878 Update deprecated functions in RF and GBT Examples
  cpp/daal/include/algorithms/decision_forest/decision_forest_classification_model_builder.h
  cpp/daal/include/algorithms/gradient_boosted_trees/gbt_classification_model_builder.h
  cpp/daal/include/algorithms/gradient_boosted_trees/gbt_regression_model_builder.h
  examples/daal/cpp/source/decision_forest/df_cls_dense_batch_model_builder.cpp
  examples/daal/cpp/source/decision_forest/df_cls_traversed_model_builder.cpp
  examples/daal/cpp/source/gradient_boosted_trees/gbt_cls_traversed_model_builder.cpp
  examples/daal/cpp/source/gradient_boosted_trees/gbt_reg_traversed_model_builder.cpp
Labels: testing, API breaking change

#2890 [bug] Coverity fixes 2025.0
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
Labels: bug

#2893 fix(samples): replace `CL/sycl.hpp` with `sycl/sycl.hpp`
  samples/oneapi/dpc/ccl/sources/knn_bf_distr_ccl.cpp
  samples/oneapi/dpc/mpi/sources/knn_bf_distr_mpi.cpp
Labels: enhancement

#2894 fix: resolve omp simd error in mdd
  dev/make/compiler_definitions/icx.mkl.32e.mk
Labels: dpc++

#2898 Change default COMPILER to icx in makefile
  dev/make/function_definitions/32e.mk
Labels: dependencies

#2896 Add DEPENDENTLOAD flag to vc linker on Windows
  dev/make/compiler_definitions/vc.mkl.32e.mk
  examples/cmake/setup_examples.cmake
  samples/cmake/setup_samples.cmake
Labels: enhancement

#2906 FIX: `Kmeans` timeouts issue on GPU for sparse inputs
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp
Labels: bug

#2909 Update docs codeowners
  .github/CODEOWNERS
Labels: docs

#2901 chore(ci): add `read` permissions for `label-enforcement` workflow
  .github/workflows/label-enforcement.yml
Labels: enhancement

#2910 fix: adding daal exports for vc compiler
  cpp/daal/src/algorithms/elastic_net/elastic_net_training_result_fpt.cpp
  cpp/daal/src/algorithms/lasso_regression/lasso_regression_training_result_fpt.cpp
  cpp/daal/src/algorithms/normalization/zscore/zscore_fpt.cpp
  cpp/daal/src/algorithms/pca/pca_partialresult_correlation_fpt.cpp
  cpp/daal/src/algorithms/pca/pca_partialresult_svd.h
  cpp/daal/src/algorithms/pca/pca_partialresult_svd_fpt.cpp
  cpp/daal/src/algorithms/pca/pca_result_fpt.cpp
  cpp/daal/src/algorithms/svd/svd_dense_default_distr_step2.h
  cpp/daal/src/algorithms/svd/svd_dense_default_distr_step2_fpt.cpp
  cpp/daal/src/algorithms/svd/svd_dense_default_distr_step3.h
  cpp/daal/src/algorithms/svd/svd_dense_default_distr_step3_fpt.cpp
Labels: bug

#2903 [enhancement] Add new issue templates
  .github/ISSUE_TEMPLATE/RFC.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs

#2899 Update Docker file
  .ci/env/apt.sh
  .ci/env/environment.yml
  dev/docker/README.md
  dev/docker/onedal-dev.Dockerfile
Labels: docs, infra

#2905 Add sycl headers to bazel toolchain config for DPCPP through icx
  dev/bazel/toolchains/cc_toolchain_lnx.bzl
Labels: dpc++, infra

#2828 MAINT: updated github PR templates
  .github/pull_request_template.md
  .github/workflows/pr-checklist.yml
Labels: docs

#2914 First version of RFC process
  .gitattributes
  .github/CODEOWNERS
  .github/workflows/slack-pr-notification.yml
  .gitignore
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  rfcs/template.md
Labels: RFC

#2927 Fix for getting of description for PR Checklist job
  .github/workflows/pr-checklist.yml
Labels: infra

#2916 Introducing oneDAL roles for contributors and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: enhancement
