Repository uxlfoundation/oneDAL, pull requests merged in 2024-11, with the labels that each got.

#2965 dev: update bazel oneMKL deps
  WORKSPACE
  dev/bazel/deps/tbb.bzl
Labels: dependencies

#2946 fix(make): enabling debug build
  cpp/daal/src/algorithms/dtrees/dtrees_feature_type_helper.h
  dev/make/compiler_definitions/dpcpp.mk
  dev/make/compiler_definitions/icx.mkl.32e.mk
  makefile
Labels: bug

#2967 fix: add cycle linking for mkl_core(bazel)
  .ci/pipeline/ci.yml
  dev/bazel/deps/mkl.tpl.BUILD
Labels: bug, dependencies

#2969 DOC: Update instructions for installing from source
  INSTALL.md
Labels: docs

#2971 [CI] make Nightly-build CI run on changes to CI
  .ci/env/apt.sh
  .github/workflows/nightly-build.yml
  dev/make/compiler_definitions/dpcpp.mk
Labels: infra

#2973 DOC: Fix link to example that was moved
  docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
Labels: docs

#2970 fix: remove libonedal_sycl.a from makefile
  BUILD
  cmake/templates/oneDALConfig.cmake.in
  dev/bazel/deps/onedal.bzl
  dev/bazel/deps/onedal.tpl.BUILD
  docs/source/get-started/build-and-run-examples.rst
  docs/source/onedal/build_app/build-application.rst
  makefile
  samples/oneapi/dpc/ccl/CMakeLists.txt
  samples/oneapi/dpc/ccl/makefile_lnx
  samples/oneapi/dpc/mpi/CMakeLists.txt
  samples/oneapi/dpc/mpi/makefile_lnx
Labels: dependencies

#2979 fix: Set the correct CPATH for oneAPI toolkit
  deploy/local/vars_lnx.sh
  deploy/local/vars_win.bat
Labels: bug

#2980 MAINT: Add vscode workspace files to gitignore
  .gitignore
Labels: enhancement

#2959 Replace internally developed CSR GEMM with a call to MKL
  cpp/oneapi/dal/algo/basic_statistics/test/fixture.hpp
  cpp/oneapi/dal/algo/kmeans/BUILD
  cpp/oneapi/dal/algo/kmeans/backend/gpu/empty_cluster_handling.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/empty_cluster_handling_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/infer_kernel_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_csr_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/test/batch.cpp
  cpp/oneapi/dal/algo/kmeans/test/fixture.hpp
  cpp/oneapi/dal/algo/logistic_regression/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
  cpp/oneapi/dal/test/engine/csr_table_builder.hpp
Labels: enhancement

#2984 FIX: Fix histogram reduction when number of tasks is larger than input data
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_helpers.hpp
Labels: dpc++

#2976 ENH: Implement GPU version of spectral decomposition as linear regression fallback
  cpp/oneapi/dal/algo/linear_regression/test/batch.cpp
  cpp/oneapi/dal/algo/linear_regression/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/lapack/solve_dpc.cpp
  cpp/oneapi/dal/detail/error_messages.cpp
  cpp/oneapi/dal/detail/error_messages.hpp
Labels: dpc++

#2986 Revert SPMD K-means instantiation to fix #2959
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops_dpc.cpp
Labels: bug

#2981 update version to 2025.2.0
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#2987 Add ability of vtune profiling
  INSTALL.md
  cpp/daal/src/externals/service_profiler.cpp
  cpp/daal/src/externals/service_profiler.h
  makefile
Labels: enhancement

#2991 Fix rule of three violations in AlgorithmContainer classes
  cpp/daal/include/algorithms/algorithm_container_base.h
  cpp/daal/include/algorithms/algorithm_container_base_batch.h
Labels: interfaces
