Repository uxlfoundation/oneDAL, pull requests merged in 2024-10, with the labels that each got.

#2871 Adding OpenRNG Backend
  .ci/env/openrng.sh
  .ci/scripts/build.sh
  cpp/daal/src/externals/service_rng_openrng.h
  cpp/daal/src/externals/service_rng_ref.h
  dev/make/compiler_definitions/gnu.ref.arm.mk
  dev/make/deps.ref.mk
  dev/make/function_definitions/lnx32e.mk
  dev/make/function_definitions/lnxarm.mk
  makefile
Labels: enhancement

#2922 [maint] Update docker ubuntu version to 24.04
  cpp/oneapi/dal/algo/knn/detail/distance.hpp
  cpp/oneapi/dal/algo/objective_function/detail/objective.hpp
  cpp/oneapi/dal/algo/svm/detail/kernel_function.hpp
  dev/docker/onedal-dev.Dockerfile
Labels: infra

#2926 feature: adding -fsycl-max-parallel-link-jobs in make
  dev/make/compiler_definitions/dpcpp.mk
  makefile
Labels: enhancement, infra

#2934 Add copyright to MAINTAINERS
  MAINTAINERS.md
Labels: docs

#2921 Fix broken links 2025.0
  docs/source/daal/algorithms/decision_forest/decision-forest-classification.rst
  docs/source/daal/algorithms/gradient_boosted_trees/gradient-boosted-trees-classification.rst
  docs/source/daal/algorithms/gradient_boosted_trees/gradient-boosted-trees-regression.rst
  docs/source/daal/algorithms/linear_ridge_regression/linear-regression.rst
  docs/source/daal/algorithms/svm/support-vector-machine-classifier.rst
  docs/source/daal/algorithms/svm_multi_class/multi-class-classifier.rst
  docs/source/daal/data-management/data-sources.rst
Labels: docs

#2917 SVE optimised float WSSJ kernel
  cpp/daal/src/algorithms/svm/svm_train_common_impl.i
  cpp/daal/src/algorithms/svm/svm_train_common_sve_impl.i
Labels: enhancement, perf

#2939 [fix] pin github actions upload-artifact to v4.4.0 to preserve linux symlinks
  .github/workflows/nightly-build.yml
Labels: bug, infra

#2935 Fixes for PR checklist workflow
  .github/workflows/pr-checklist.yml
Labels: infra

#2928 feature: dynamic setting deps layouts
  .ci/pipeline/ci.yml
  .github/workflows/nightly-build.yml
  makefile
  samples/daal/cpp/mpi/makefile_lnx
  samples/daal/cpp/mysql/makefile_lnx
  samples/oneapi/dpc/ccl/makefile_lnx
  samples/oneapi/dpc/mpi/makefile_lnx
Labels: infra

#2943 feature: adding -fsycl-max-parallel-link-jobs in bazel
  dev/bazel/deps/mkl.tpl.BUILD
Labels: enhancement

#2941 update version to 2025.1.0
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#2930 Use spectral decomposition as more accurate fallback from Cholesky
  cpp/daal/src/algorithms/service_kernel_math.h
  cpp/daal/src/externals/service_lapack.h
  cpp/daal/src/externals/service_lapack_declar_ref.h
  cpp/daal/src/externals/service_lapack_mkl.h
  cpp/daal/src/externals/service_lapack_ref.h
  cpp/oneapi/dal/algo/linear_regression/test/batch.cpp
  cpp/oneapi/dal/algo/linear_regression/test/fixture.hpp
Labels: enhancement

#2938 [enhancement] Store windows basekit with symlink-preserving compression for nightly-build
  .github/workflows/nightly-build.yml
Labels: infra

#2895 xcp ref implementation
  cpp/daal/src/externals/service_stat_ref.h
Labels: enhancement

#2955 update version to 2025.0.1
  dev/bazel/config/config.bzl
  makefile.ver
Labels: infra

#2951 fix: workaround for Knn KD tree
  cpp/daal/src/algorithms/k_nearest_neighbors/kdtree_knn_classification_train_dense_default_impl.i
Labels: bug

#2952 [fix] add missing headers for finiteness_checker algorithm
  cpp/oneapi/dal.hpp
  cpp/oneapi/dal/algo/finiteness_checker.hpp
Labels: bug

#2958 Update oneAPI components versions in CI
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  .ci/scripts/build.sh
Labels: infra, dependencies

#2960 [CI] fix Nightly-build following on #2958
  .github/workflows/nightly-build.yml
Labels: infra

#2949 FIX(make): fix incremental builds by only releasing updated headers
  makefile.ver
Labels: bug

#2961 [CI] store .ci/env as environment for sklearnex GitHub Actions CI
  .github/workflows/nightly-build.yml
Labels: infra

#2963 2025 fix
  docs/source/deprecation.rst
  docs/source/index.rst
  docs/source/onedal/algorithms/clustering/kmeans.rst
  docs/source/onedal/algorithms/decomposition/pca.rst
  docs/source/onedal/gpu_support.rst
  docs/source/onedal/introduction.rst
  docs/source/onedal/spmd/index.rst
Labels: docs

#2964 [CI] Windows basekit upgrade 2025.0
  .ci/pipeline/ci.yml
  .github/workflows/nightly-build.yml
Labels: infra
