Repository uxlfoundation/oneDAL, pull requests merged in 2025-03, with the labels that each got.

#3097 [backport: rls/2025.4.0-rls] chore(dev): allow bazel to use different versions of OpenCL lib (#3089)
  dev/bazel/deps/opencl.tpl.BUILD
Labels: enhancement

#3059 Adding correlation distance metric in oneDAL primitives
  cpp/oneapi/dal/backend/primitives/distance/BUILD
  cpp/oneapi/dal/backend/primitives/distance/correlation_distance_dpc.cpp
  cpp/oneapi/dal/backend/primitives/distance/correlation_distance_misc.hpp
  cpp/oneapi/dal/backend/primitives/distance/correlation_distance_misc_dpc.cpp
  cpp/oneapi/dal/backend/primitives/distance/distance.hpp
  cpp/oneapi/dal/backend/primitives/distance/metrics.hpp
  cpp/oneapi/dal/backend/primitives/distance/test/correlation_distance_dpc.cpp
Labels: dpc++, oneAPI

#3110 Fix sparse K-means failure on PVC when the number of rows in large
  cpp/oneapi/dal/algo/kmeans/backend/gpu/kernels_csr_impl.hpp
  cpp/oneapi/dal/algo/kmeans/backend/gpu/train_kernel_lloyd_csr_dpc.cpp
  cpp/oneapi/dal/algo/kmeans/test/batch.cpp
Labels: bug, dpc++

#3108 feature: doc automation for onedal
  .github/workflows/docs-release.yml
Labels: documentation

#3109 DOC: Replace oneAPI logo with UXL
  docs/source/_static/favicons.png
  docs/source/_static/oneAPI-rgb-rev-100.png
  docs/source/_static/uxl-foundation-logo-horizontal-color.png
  docs/source/conf.py
Labels: documentation

#3115 Rolled back bazel to 7.4.1
  .bazelrc
  .bazelversion
  MODULE.bazel
  MODULE.bazel.tmp
  WORKSPACE
  dev/bazel/config/config.bzl
  dev/bazel/toolchains/cc_toolchain.bzl
  dev/bazel/toolchains/cc_toolchain_extension.bzl
  dev/bazel/toolchains/cc_toolchain_lnx.bzl
  dev/bazel/toolchains/common.bzl
  dev/bazel/toolchains/extra_toolchain.bzl
  dev/bazel/toolchains/extra_toolchain_extension.bzl
Labels: bug

#3117 Reduce memory requirements of sparse K-means test
  cpp/oneapi/dal/algo/kmeans/test/batch.cpp
Labels: dpc++

#3102 [CI, Enhancement] Refine github actions dpcpp linux make build using AVX512 and debug symbols
  .ci/scripts/build.sh
  .ci/scripts/test.sh
  .github/workflows/ci.yml
  INSTALL.md
  makefile
Labels: infra

#3077 [CI, enhancement] track oneTBB using renovatebot
  .ci/env/tbb.bat
  .ci/env/tbb.sh
  .github/renovate.json
Labels: infra

#3125 DOC: Remove broken instructions for building with conda environments on windows
  INSTALL.md
Labels: docs

#3122 Fix outlier detection assignment operators (rule of three violation, Coverity)
  cpp/daal/include/algorithms/outlier_detection/outlier_detection_bacon_types.h
  cpp/daal/include/algorithms/outlier_detection/outlier_detection_multivariate_types.h
  cpp/daal/include/algorithms/outlier_detection/outlier_detection_univariate_types.h
  cpp/daal/src/algorithms/outlierdetection_bacon/outlierdetection_bacon.cpp
  cpp/daal/src/algorithms/outlierdetection_multivariate/outlierdetection_multivariate.cpp
  cpp/daal/src/algorithms/outlierdetection_univariate/outlier_detection_univariate.cpp
Labels: enhancement

#3127 Regression algorithm Coverity fixes (rule-of-three violation)
  cpp/daal/include/algorithms/regression/regression_predict_types.h
  cpp/daal/include/algorithms/regression/regression_training_types.h
  cpp/daal/src/algorithms/regression/regression_prediction_batch.cpp
  cpp/daal/src/algorithms/regression/regression_training_input.cpp
Labels: enhancement

#3046 feature(rf optimizations): enabling oneDPL and sort primitive refactoring
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  INSTALL.md
  MODULE.bazel
  cpp/oneapi/dal.hpp
  cpp/oneapi/dal/BUILD
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_feature_type_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_service_kernels.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_service_kernels_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/common.cpp
  cpp/oneapi/dal/algo/decision_forest/common.hpp
  cpp/oneapi/dal/algo/decision_forest/test/spmd.cpp
  cpp/oneapi/dal/backend/primitives/rng/device_engine.hpp
  cpp/oneapi/dal/backend/primitives/rng/device_engine_dpc.cpp
  cpp/oneapi/dal/backend/primitives/rng/host_engine.hpp
  cpp/oneapi/dal/backend/primitives/rng/host_engine_collection.hpp
  cpp/oneapi/dal/backend/primitives/rng/rng_types.hpp
  cpp/oneapi/dal/backend/primitives/rng/test/rng_dpc.cpp
  cpp/oneapi/dal/backend/primitives/sort/sort.hpp
  cpp/oneapi/dal/backend/primitives/sort/sort_dpc.cpp
  cpp/oneapi/dal/rng.hpp
  dev/bazel/deps/dpl.bzl
  dev/bazel/deps/dpl.tpl.BUILD
  makefile
Labels: dpc++, dependencies

#3135 [bug] fix intermittent failures in LinuxMakeDPCPP(AVX512) github action
  makefile
  makefile.ver
Labels: bug, infra

#3112 [CI, enhancement] enforce ABI checking of linux DPCPP build
  .ci/env/apt.sh
  .ci/scripts/abi_check.sh
  .github/.abignore
  .github/workflows/ci.yml
Labels: infra

#3137 DOC: Remove redundant instruction for `conda`
  INSTALL.md
Labels: docs

#3140 [bug] fix abi check to not fail for all changes in ABI, just breaking ones
  .ci/scripts/abi_check.sh
Labels: bug, enhancement, infra

#3143 Fix rule of three violations in Linear Regression
  cpp/daal/include/algorithms/analysis.h
  cpp/daal/include/algorithms/linear_model/linear_model_model.h
  cpp/daal/include/algorithms/linear_model/linear_model_predict_types.h
  cpp/daal/include/algorithms/linear_model/linear_model_training_types.h
  cpp/daal/include/algorithms/linear_regression/linear_regression_training_types.h
  cpp/daal/src/algorithms/linear_model/linear_model_model.cpp
  cpp/daal/src/algorithms/linear_model/linear_model_predict_batch.cpp
  cpp/daal/src/algorithms/linear_model/linear_model_training_input.cpp
  cpp/daal/src/algorithms/linear_regression/linear_regression_group_of_betas_dense_default_batch_kernel.h
  cpp/daal/src/algorithms/linear_regression/linear_regression_single_beta_dense_default_batch_kernel.h
  cpp/daal/src/algorithms/linear_regression/linear_regression_training_input.cpp
Labels: enhancement

#3045 Updated globs for bazel 8.0.0
  .bazelrc
  cpp/daal/BUILD
  cpp/daal/src/algorithms/dtrees/forest/classification/BUILD
  cpp/daal/src/algorithms/dtrees/forest/regression/BUILD
  cpp/oneapi/dal/algo/covariance/BUILD
  cpp/oneapi/dal/algo/dbscan/BUILD
  cpp/oneapi/dal/algo/decision_forest/backend/cpu/BUILD
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/BUILD
  cpp/oneapi/dal/algo/finiteness_checker/BUILD
  cpp/oneapi/dal/algo/kmeans/BUILD
  cpp/oneapi/dal/algo/linear_kernel/BUILD
  cpp/oneapi/dal/algo/pca/BUILD
  cpp/oneapi/dal/algo/polynomial_kernel/BUILD
  cpp/oneapi/dal/algo/rbf_kernel/BUILD
  cpp/oneapi/dal/algo/sigmoid_kernel/BUILD
  cpp/oneapi/dal/backend/primitives/BUILD
  cpp/oneapi/dal/backend/primitives/regression/BUILD
  cpp/oneapi/dal/backend/primitives/rng/BUILD
  cpp/oneapi/dal/backend/primitives/search/BUILD
  cpp/oneapi/dal/backend/primitives/sparse_blas/BUILD
  cpp/oneapi/dal/backend/primitives/voting/BUILD
  dev/bazel/daal.bzl
  dev/bazel/dal.bzl
  dev/bazel/deps/ccl.tpl.BUILD
Labels: enhancement

#3146 [CI, enhancement] set compute runtime GPU settings to improve GPU runner stability
  .github/workflows/ci.yml
Labels: enhancement, infra

#3147 [docs] add missing documentation of gcov support from #3010
  INSTALL.md
  makefile
Labels: docs

#3144 [fix] add copy assignment operator to quantiles (coverity fix)
  cpp/daal/include/algorithms/quantiles/quantiles_types.h
  cpp/daal/src/algorithms/quantiles/quantiles.cpp
Labels: enhancement

#3074 [Enhancement] Add float datatype support to rocAucScore
  cpp/daal/include/data_management/data/internal/roc_auc_score.h
  cpp/daal/src/data_management/roc_auc_score.cpp
Labels: enhancement
