Repository uxlfoundation/oneDAL, pull requests merged in 2025-02, with the labels that each got.

#3060 update version to 2025.4.0
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#3061 DOC: Add list of ideas for potential contributors
  docs/source/contribution/ideas.rst
  docs/source/index-toc.rst
Labels: docs

#3069 Resolve Symbol Conflicts Between oneMKL and oneDAL
  dev/make/common.mk
  dev/make/deps.mkl.mk
  dev/make/deps.ref.mk
Labels: infra

#3075 [CI] Remove license header from PR template
  .github/.licenserc.yaml
  .github/pull_request_template.md
Labels: infra

#3072 Fix DAAL examples build failures with C++20
  cpp/daal/include/algorithms/covariance/covariance_distributed.h
  cpp/daal/include/algorithms/linear_regression/linear_regression_training_distributed.h
  cpp/daal/include/algorithms/linear_regression/linear_regression_training_types.h
  cpp/daal/include/algorithms/ridge_regression/ridge_regression_training_distributed.h
  cpp/oneapi/dal/detail/common.hpp
Labels: bug

#3073 [CI, enhancement] move DPCPP CI to self-hosted github runner
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  .github/workflows/ci.yml
Labels: infra

#3071 FIX: addressing Coverity hits on Ridge
  cpp/daal/include/algorithms/ridge_regression/ridge_regression_predict_types.h
  cpp/daal/include/algorithms/ridge_regression/ridge_regression_training_types.h
  cpp/daal/src/algorithms/ridge_regression/ridge_regression_prediction_batch.cpp
  cpp/daal/src/algorithms/ridge_regression/ridge_regression_training_input.cpp
Labels: enhancement

#3083 Fixing new Coverity hits on ridge - rule of three
  cpp/daal/include/algorithms/ridge_regression/ridge_regression_training_types.h
Labels: enhancement

#3081 Remove redundant gradient computation in backtracking algorithm
  cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors.hpp
  cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors_dpc.cpp
  cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/objective_function/test/spmd_fixture.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/common.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
Labels: enhancement, dpc++

#3058 ENH: Non-batched linear regression for high-dimensional problems
  cpp/daal/src/algorithms/linear_model/linear_model_hyperparameter_impl.h
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
  cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter.cpp
  cpp/daal/src/algorithms/linear_regression/linear_regression_hyperparameter_impl.h
  cpp/daal/src/externals/service_blas.h
  cpp/daal/src/externals/service_blas_declar_ref.h
  cpp/daal/src/externals/service_blas_mkl.h
  cpp/daal/src/externals/service_blas_ref.h
  cpp/oneapi/dal/algo/linear_regression/backend/cpu/finalize_train_kernel_norm_eq.cpp
  cpp/oneapi/dal/algo/linear_regression/backend/cpu/partial_train_kernel_norm_eq.cpp
  cpp/oneapi/dal/algo/linear_regression/backend/cpu/train_kernel_common.hpp
  cpp/oneapi/dal/algo/linear_regression/backend/cpu/train_kernel_norm_eq.cpp
  cpp/oneapi/dal/algo/linear_regression/parameters/cpu/train_parameters.cpp
  cpp/oneapi/dal/algo/linear_regression/test/batch.cpp
  cpp/oneapi/dal/algo/linear_regression/test/fixture.hpp
  cpp/oneapi/dal/algo/linear_regression/test/online.cpp
  cpp/oneapi/dal/algo/linear_regression/test/train_parameters.cpp
  cpp/oneapi/dal/algo/linear_regression/train_types.cpp
  cpp/oneapi/dal/algo/linear_regression/train_types.hpp
  cpp/oneapi/dal/test/engine/fixtures.hpp
Labels: enhancement

#3095 fix: add isValid() method for dtrees ModelImpl
  cpp/daal/src/algorithms/dtrees/dtrees_model.cpp
  cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h
Labels: bug

#3082 ci: pin some dependencies by hash
  .ci/env/apt.sh
  .github/workflows/ci.yml
Labels: infra

#3026 Add proper CPUID eax checking
  cpp/daal/src/services/compiler/generic/env_detect_features.cpp
  cpp/daal/src/services/service_defines.h
  cpp/oneapi/dal/detail/cpu.cpp
Labels: enhancement

#3079 [enhancement] SVE Implementation of sumWithSIMD
  cpp/daal/src/data_management/finiteness_checker_cpu.cpp
  cpp/daal/src/data_management/finiteness_checker_sve_impl.i
Labels: enhancement
