Repository uxlfoundation/oneDAL, pull requests merged in 2025-06, with the labels that each got.

#3233 CI: Print correct version of clang-format being executed
  .ci/scripts/clang-format.sh
Labels: infra

#3245 DOC: Better description of what oneDAL does
  README.md
  docs/source/index.rst
Labels: documentation

#3244 FIX: Update links that have moved
  README.md
  docs/source/examples.rst
Labels: documentation

#3241 [CI] remove arm cross compile azure pipelines runners
  .ci/env/arm-clang-crosscompile-toolchain.cmake
  .ci/env/arm-gnu-crosscompile-toolchain.cmake
  .ci/pipeline/ci.yml
Labels: infra

#3252 DOC: Remove note about MKL FPK
  README.md
Labels: documentation

#3216 [CI, enhancement] add windows sklearnex azure pipelines template
  .ci/pipeline/ci.yml
Labels: infra

#3204 ci: add `cve-bin-tool` scan to nightly build
  .github/workflows/nightly-build.yml
Labels: enhancement, infra

#3267 [bugfix] separate stability issues of ```intel/cve-bin-tool-action``` from nightly-build
  .github/workflows/nightly-build.yml
  .github/workflows/nightly-test.yml
Labels: infra

#3227 MAINT: Reuse common routines in covariance
  cpp/daal/src/algorithms/covariance/covariance_impl.i
  cpp/daal/src/externals/service_math.h
  cpp/daal/src/externals/service_math_mkl.h
  cpp/daal/src/externals/service_math_ref.h
Labels: enhancement

#3256 [bug] fix shared library AddressSanitizer integration for the gnu compiler
  dev/make/compiler_definitions/clang.mk
  dev/make/compiler_definitions/dpcpp.mk
  dev/make/compiler_definitions/gnu.mk
  dev/make/compiler_definitions/icx.mkl.32e.mk
  dev/make/compiler_definitions/vc.mkl.32e.mk
  makefile
Labels: bug

#3139 init parallel trees method
  cpp/daal/src/algorithms/dtrees/dtrees_model_impl.h
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model.cpp
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_model_impl.h
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_model.cpp
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_model_impl.h
  cpp/daal/src/algorithms/regression/regression_model_impl.h
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_model_manager.hpp
  cpp/oneapi/dal/algo/decision_forest/common.cpp
  cpp/oneapi/dal/algo/decision_forest/common.hpp
Labels: dpc++
