Repository uxlfoundation/oneDAL, pull requests merged in 2025-04, with the labels that each got.

#3076 [CI] Update openBLAS to v0.3.29
  .ci/env/openblas.sh
  .github/renovate.json
Labels: infra

#3150 [bugfix] remove a blank line in modules
  deploy/local/dal
Labels: bug

#3148 [enhancement] Add ability to integrate sanitizers in oneDAL Make builds
  INSTALL.md
  makefile
Labels: enhancement, infra

#3149 [bugfix] make makefile.ver work with POSIX shells
  makefile.ver
Labels: bug

#3156 Update CMake version in examples to 3.5
  examples/daal/cpp/CMakeLists.txt
  examples/oneapi/cpp/CMakeLists.txt
  examples/oneapi/dpc/CMakeLists.txt
Labels: bug

#3154 Remove dispatching to SSE2 code path on non-intel x86 CPUs
  cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_hist_batch_fpt_dispatcher.cpp
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_hist_batch_fpt_dispatcher.cpp
  cpp/daal/src/algorithms/kernel_config.h
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial_csr_fast_batch_fpt_dispatcher.cpp
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_polynomial_dense_default_batch_fpt_dispatcher.cpp
  cpp/daal/src/algorithms/svm/svm_train_thunder_batch_fpt_dispatcher.cpp
  cpp/daal/src/algorithms/tsne/tsne_gradient_descent_fpt.cpp
  cpp/daal/src/data_management/roc_auc_score.cpp
  cpp/daal/src/externals/service_dispatch.h
Labels: enhancement

#3124 Fix decision tree coverity hits
  cpp/oneapi/dal/algo/decision_tree/backend/node_info_impl.hpp
  cpp/oneapi/dal/algo/decision_tree/common.hpp
Labels: enhancement

#3152 Fixing new Coverity hits on KNN
  cpp/daal/include/algorithms/k_nearest_neighbors/bf_knn_classification_model.h
  cpp/daal/include/algorithms/k_nearest_neighbors/bf_knn_classification_training_types.h
  cpp/daal/include/algorithms/k_nearest_neighbors/kdtree_knn_classification_model.h
  cpp/oneapi/dal/algo/knn/backend/model_impl.hpp
Labels: bug

#3158 FIX: Fix potential non-definitiness of BFGS approximation
  cpp/daal/src/algorithms/optimization_solver/lbfgs/lbfgs_dense_default_impl.i
Labels: bug

#3162 DOC: Remove suggestion to use to daal4py in readme (v2)
  README.md
Labels: documentation

#3163 DOC: Add instructions for DPL on conda
  INSTALL.md
Labels: documentation

#3164 [CI] Update Windows BaseKit, Windows OpenCL Runtime installs to 2025.1
  .ci/pipeline/ci.yml
  .ci/scripts/collect_opencl_rt.ps1
Labels: infra

#3160 [bugfix] make shared-libasan default option for ```REQSAN=address```
  makefile
Labels: bug, enhancement

#3169 ENH: Parallelize doc build by default
  docs/Makefile
Labels: documentation

#3168 DOC: Fix broken link to logreg builder
  docs/source/daal/algorithms/logistic_regression/logistic-regression.rst
Labels: documentation

#3157 Updated OpenCL dependencies for MKL
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  dev/bazel/deps/mkl.tpl.BUILD
  dev/bazel/deps/opencl.tpl.BUILD
  examples/oneapi/cpp/BUILD
Labels: dependencies

#3171 DOC: Update third-party-program files
  third-party-programs-mkl.txt
  third-party-programs.txt
Labels: documentation

#3174 fix: remove dead code
  cpp/daal/include/algorithms/qr/qr_distributed.h
Labels: enhancement

#3173 fix: static cast uniqueDepth to int to avoid ull underflow
  cpp/daal/src/algorithms/dtrees/gbt/treeshap.cpp
Labels: enhancement

#3159 Use aligned loads and stores where possible in DAAL memory management
  cpp/daal/include/services/daal_defines.h
  cpp/daal/src/externals/service_memory.cpp
  cpp/daal/src/externals/service_memory.h
  dev/bazel/daal.bzl
Labels: perf

#3181 Revert "fix: static cast uniqueDepth to int to avoid ull underflow (#…
  cpp/daal/src/algorithms/dtrees/gbt/treeshap.cpp
Labels: bug

#3176 [CI] swap uxl self-hosted runners to github hosted
  .github/workflows/ci.yml
Labels: infra

#3183 replace CPATH variable with CPLUS_INCLUDE_PATH
  deploy/local/dal
  deploy/local/vars_lnx.sh
  deploy/local/vars_mac.sh
  deploy/local/vars_win.bat
  docs/source/get-started/build-and-run-examples.rst
Labels: infra

#3186 fix(docs): Install dependencies fails over debian-installed packages
  .ci/pipeline/docs.yml
Labels: bug, docs

#3155 feature: onedal verbose profiler
  cpp/daal/include/services/internal/service_profiler.h
  cpp/daal/src/algorithms/covariance/covariance_dense_batch_impl.i
  cpp/daal/src/algorithms/covariance/covariance_impl.i
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/kmeans/kmeans_lloyd_batch_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_finalize_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
  cpp/daal/src/algorithms/logistic_regression/logistic_regression_train_dense_default_impl.i
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_estimates_batch.i
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_estimates_online.i
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_kernel.h
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_online_impl.i
  cpp/daal/src/algorithms/objective_function/common/objective_function_utils.i
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/optimization_solver/sgd/sgd_dense_minibatch_impl.i
  cpp/daal/src/algorithms/pca/pca_dense_correlation_batch_impl.i
  cpp/daal/src/algorithms/service_kernel_math.h
  cpp/daal/src/algorithms/svm/svm_train_boser_cache.i
  cpp/daal/src/algorithms/svm/svm_train_boser_impl.i
  cpp/daal/src/algorithms/svm/svm_train_common.h
  cpp/daal/src/algorithms/svm/svm_train_common_impl.i
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_cache.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/algorithms/svm/svm_train_thunder_workset.h
  cpp/daal/src/externals/service_memory.cpp
  cpp/daal/src/externals/service_memory.h
  cpp/daal/src/externals/service_profiler.cpp
  cpp/daal/src/externals/service_profiler.h
  cpp/daal/src/services/library_version_info.cpp
  cpp/oneapi/dal/algo/covariance/backend/cpu/finalize_compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/covariance/backend/cpu/partial_compute_kernel_dense.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/compute_kernel_dense_impl_dpc.cpp
  cpp/oneapi/dal/algo/covariance/backend/gpu/misc.hpp
  cpp/oneapi/dal/algo/decision_forest/backend/gpu/train_kernel_hist_impl_dpc.cpp
  cpp/oneapi/dal/backend/primitives/blas/gemm_dpc.cpp
  cpp/oneapi/dal/backend/primitives/utils.hpp
  cpp/oneapi/dal/detail/profiler.cpp
  cpp/oneapi/dal/detail/profiler.hpp
  docs/source/contribution/profiling.rst
  docs/source/index-toc.rst
Labels: dpc++
