Repository uxlfoundation/oneDAL, pull requests merged in 2025-01, with the labels that each got.

#3033 DOC: Fix incorrect bash syntax in conda build instructions
  INSTALL.md
Labels: docs

#3025 Fix Coverity hits for PCA
  cpp/daal/include/algorithms/pca/pca_explained_variance_batch.h
  cpp/daal/include/algorithms/pca/pca_types.h
  cpp/daal/src/algorithms/pca/pca_input.cpp
  cpp/daal/src/algorithms/pca/pca_result_impl.h
Labels: enhancement

#3021 MAINT: Ignore config files from file explorers
  .gitignore
Labels: infra

#3037 Fix GCC build errors in PCA example
  cpp/daal/include/algorithms/algorithm_types.h
  cpp/daal/include/data_management/data/data_dictionary.h
  cpp/daal/src/algorithms/algorithm_base_impl.cpp
Labels: bug

#3008 Documentation for oneAPI data management backend primitives
  cpp/oneapi/dal/array.hpp
  cpp/oneapi/dal/backend/primitives/ndarray.hpp
  cpp/oneapi/dal/backend/primitives/ndshape.hpp
  cpp/oneapi/dal/backend/primitives/utils.hpp
  docs/dalapi/directives.py
  docs/dalapi/doxypy/index.py
  docs/doxygen/oneapi/Doxyfile
  docs/source/api/data-management/backend-primitives.rst
  docs/source/api/data-management/backend/ndarray.rst
  docs/source/api/data-management/backend/ndview.rst
  docs/source/api/data-management/index.rst
  docs/source/conf.py
  docs/source/contribution/cpu_features.rst
  docs/source/includes/cpu-features/abc-classification-train-kernel.rst
  docs/source/includes/cpu-features/abc-classification-train-method1-fpt-cpu.rst
  docs/source/includes/cpu-features/abc-classification-train-method1-impl.rst
  docs/source/includes/cpu-features/abc-classification-train-method2-impl.rst
  docs/source/onedal/data-management/backend-primitives.rst
  docs/source/onedal/data-management/index.rst
Labels: docs

#3043 DOC: Fix command for installing conda dependencies
  INSTALL.md
Labels: docs

#3028 DOC: Conda instructions for other platforms
  INSTALL.md
Labels: docs

#3044 DOC: Fix typo in documentation
  docs/source/get-started/build-and-run-examples.rst
Labels: docs

#3047 Fix min, max and sum_squares computations in low order moments
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_impl.i
Labels: bug

#3048 FIX: Fix incorrect mapping of thread IDs
  cpp/daal/src/threading/threading.cpp
Labels: bug

#3049 MAINT: Add assignment operators for Input and Parameter classes of solvers
  cpp/daal/include/algorithms/optimization_solver/adagrad/adagrad_types.h
  cpp/daal/include/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.h
  cpp/daal/include/algorithms/optimization_solver/iterative_solver/iterative_solver_types.h
  cpp/daal/include/algorithms/optimization_solver/lbfgs/lbfgs_types.h
  cpp/daal/include/algorithms/optimization_solver/objective_function/cross_entropy_loss_types.h
  cpp/daal/include/algorithms/optimization_solver/objective_function/logistic_loss_types.h
  cpp/daal/include/algorithms/optimization_solver/objective_function/mse_types.h
  cpp/daal/include/algorithms/optimization_solver/objective_function/objective_function_types.h
  cpp/daal/include/algorithms/optimization_solver/objective_function/sum_of_functions_types.h
  cpp/daal/include/algorithms/optimization_solver/saga/saga_types.h
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_types.cpp
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_types.cpp
  cpp/daal/src/algorithms/objective_function/mse/mse_types.cpp
  cpp/daal/src/algorithms/objective_function/objective_function_types.cpp
  cpp/daal/src/algorithms/objective_function/sum_of_functions_types.cpp
  cpp/daal/src/algorithms/optimization_solver/adagrad/adagrad_types.cpp
  cpp/daal/src/algorithms/optimization_solver/coordinate_descent/coordinate_descent_types.cpp
  cpp/daal/src/algorithms/optimization_solver/iterative_solver_types.cpp
  cpp/daal/src/algorithms/optimization_solver/lbfgs/lbfgs_types.cpp
  cpp/daal/src/algorithms/optimization_solver/saga/saga_types.cpp
Labels: infra
