Repository uxlfoundation/oneDAL, pull requests merged in 2025-09, with the labels that each got.

#3341 MAINT: Remove unreachable code
  cpp/daal/include/algorithms/qr/qr_distributed.h
Labels: infra

#3339 MAINT: Avoid redundant check of error codes
  cpp/daal/src/externals/service_rng_mkl.h
Labels: infra

#3336 MAINT: Don't ignore `$CXXFLAGS` and `$LDFLAGS`
  dev/make/compiler_definitions/clang.32e.mk
  dev/make/compiler_definitions/gnu.32e.mk
  dev/make/compiler_definitions/icc.mkl.32e.mk
  dev/make/compiler_definitions/icx.mkl.32e.mk
  dev/make/compiler_definitions/vc.mkl.32e.mk
Labels: enhancement

#3338 FIX: Catch exceptions thrown during destructor calls
  cpp/daal/src/services/service_profiler.h
Labels: bug

#3354 MAINT: Add comments about what `subtractImpurity` does
  cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Labels: documentation

#3347 Fix insufficient memory allocation in csr_table conversion
  cpp/oneapi/dal/algo/basic_statistics/test/batch.cpp
  cpp/oneapi/dal/algo/basic_statistics/test/fixture.hpp
  cpp/oneapi/dal/algo/kmeans/test/batch.cpp
  cpp/oneapi/dal/algo/kmeans/test/fixture.hpp
  cpp/oneapi/dal/table/backend/interop/host_csr_table_adapter.cpp
  cpp/oneapi/dal/test/engine/csr_table_builder.hpp
Labels: bug

#3366 Fix failures in kmeans::test_batch_dpc
  cpp/oneapi/dal/backend/interop/table_conversion.hpp
Labels: bug

#3364 Fix ONEDAL_ASSERT failure triggered by empty table serialization
  cpp/daal/include/data_management/data/data_archive.h
Labels: bug
