Repository uxlfoundation/oneDAL, pull requests merged in 2025-05, with the labels that each got.

#3188 Revert "[CI] swap uxl self-hosted runners to github hosted"
  .github/workflows/ci.yml
Labels: infra

#3189 fix: CPLUS_INCLUDE_PATH lnx hotfix
  deploy/local/vars_lnx.sh
Labels: bug

#3184 DOC: Update copyright info and fix ignored options
  docs/source/conf.py
Labels: docs, documentation

#3126 Use parallel reduce threading primitive in covariance algorithm
  cpp/daal/include/services/cpu_type.h
  cpp/daal/include/services/daal_defines.h
  cpp/daal/include/services/env_detect.h
  cpp/daal/include/services/internal/daal_load_win_dynamic_lib.h
  cpp/daal/src/algorithms/covariance/covariance_impl.i
  cpp/daal/src/externals/core_threading_win_dll.cpp
  cpp/daal/src/services/service_allocators.h
  cpp/daal/src/services/service_defines.h
  cpp/daal/src/services/service_deleters.h
  cpp/daal/src/services/service_unique_ptr.h
  cpp/daal/src/services/service_utils.h
  cpp/daal/src/threading/threading.cpp
  cpp/daal/src/threading/threading.h
  cpp/oneapi/dal/detail/global_context_impl.cpp
  docs/source/contribution/threading.rst
  docs/source/includes/threading/dot-parallel-reduce-body.rst
  docs/source/includes/threading/dot-parallel-reduce.rst
Labels: enhancement, perf

#3119 Fix for copy_without_assign Coverity hits.
  cpp/daal/include/algorithms/kernel_function/kernel_function_types.h
  cpp/daal/include/algorithms/kernel_function/kernel_function_types_linear.h
  cpp/daal/include/algorithms/kernel_function/kernel_function_types_rbf.h
  cpp/daal/src/algorithms/kernel_function/kernel_function.cpp
  cpp/daal/src/algorithms/kernel_function/kernel_function_linear.cpp
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf.cpp
  cpp/daal/src/algorithms/kernel_function/polynomial/kernel_function_types_polynomial.h
Labels: enhancement

#3206 DOC: Switch to `CPLUS_INCLUDE_PATH` in conda instructions
  INSTALL.md
Labels: documentation

#3205 DOC: Correct installation instructions
  README.md
  docs/source/get-started/prerequisites.rst
  docs/source/installation.rst
Labels: documentation

#3208 DOC: Fix misrendered substitution
  docs/source/installation.rst
Labels: documentation

#3196 Fix issues with Logistic Regression and Newton-CG
  cpp/oneapi/dal/backend/primitives/objective_function/logloss_functors_dpc.cpp
  cpp/oneapi/dal/backend/primitives/objective_function/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/line_search_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/newton_cg_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/cg_solver_dpc.cpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/fixture.hpp
  cpp/oneapi/dal/backend/primitives/optimizers/test/newton_cg_dpc.cpp
Labels: bug, enhancement, dpc++

#3210 enh: replace unix2dos with sed
  .ci/env/apt.sh
  .ci/pipeline/ci.yml
  .ci/scripts/build.bat
  INSTALL.md
  makefile
Labels: infra

#3207 DOC: Add instructions for executing examples with ASAN
  INSTALL.md
Labels: documentation

#3213 [CI, enhancement] Switch an arm github actions runner to clang build
  .github/workflows/ci-aarch64.yml
Labels: enhancement, infra

#3212 fix: use github action instead of gh-pages
  .github/workflows/docs-release.yml
Labels: documentation

#3214 DOC: Use white UXL logo in dark mode
  docs/source/_static/uxl-foundation-logo-horizontal-white.png
  docs/source/conf.py
Labels: documentation

#3218 update oneDAL Version to 2025.7.0
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#3190 fix: coverity fixes for table and backend functions
  cpp/oneapi/dal/backend/common.hpp
  cpp/oneapi/dal/backend/interop/archive.hpp
  cpp/oneapi/dal/table/backend/convert/copy_convert_dpc.cpp
  cpp/oneapi/dal/table/common.hpp
Labels: bug

#3221 Fix hyperparameterIdCount in Covariance
  cpp/daal/src/algorithms/covariance/covariance_hyperparameter_impl.h
Labels: bug

#3222 fix: nightly win issue with profiler(main branch)
  cpp/daal/src/algorithms/covariance/covariance_impl.i
  cpp/daal/src/algorithms/kernel_function/kernel_function_rbf_dense_default_impl.i
  cpp/daal/src/algorithms/kmeans/kmeans_lloyd_batch_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_finalize_impl.i
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
  cpp/daal/src/algorithms/logistic_regression/logistic_regression_train_dense_default_impl.i
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_fast_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_singlepass_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_csr_sum_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_default_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_singlepass_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_batch_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_distr_step2_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_dense_sum_online_fpt_cpu.cpp
  cpp/daal/src/algorithms/low_order_moments/low_order_moments_kernel.h
  cpp/daal/src/algorithms/objective_function/cross_entropy_loss/cross_entropy_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
  cpp/daal/src/algorithms/optimization_solver/sgd/sgd_dense_minibatch_impl.i
  cpp/daal/src/algorithms/pca/pca_dense_correlation_batch_impl.i
  cpp/daal/src/algorithms/service_kernel_math.h
  cpp/daal/src/algorithms/svm/svm_train_boser_cache.i
  cpp/daal/src/algorithms/svm/svm_train_boser_impl.i
  cpp/daal/src/algorithms/svm/svm_train_common.h
  cpp/daal/src/algorithms/svm/svm_train_common_impl.i
  cpp/daal/src/algorithms/svm/svm_train_result.h
  cpp/daal/src/algorithms/svm/svm_train_thunder_impl.i
  cpp/daal/src/externals/service_memory.cpp
  cpp/daal/src/externals/service_memory.h
  cpp/daal/src/services/library_version_info.cpp
  cpp/daal/src/services/service_profiler.h
  cpp/oneapi/dal/detail/profiler.hpp
Labels: bug

#3185 Updating DisableScratchPages setting
  .github/workflows/ci.yml
Labels: infra

#3052 Downgrade nightly build to support 22.04 sklearnex testing
  .github/workflows/nightly-build.yml
Labels: infra

#3225 [CI] Update apt Linux MKL and DPCPP 2025.1, TBB 2022.1
  .ci/env/apt.sh
  .github/.abignore
Labels: infra

#3232 MAINT: Backport GH action for automated doc deployments
  .github/workflows/docs-release.yml
Labels: infra

#3236 Fix: xcsrmv computation wrong arguments
  cpp/daal/src/externals/service_spblas_mkl.h
Labels: bug
