Repository uxlfoundation/oneDAL, pull requests merged in 2025-07, with the labels that each got.

#3280 Update bazel dependency handling for Catch2 and fmt
  MODULE.bazel
  dev/bazel/deps/fmt.tpl.BUILD
Labels: dependencies

#3281 FIX: Initialize pointer to null in topology struct
  cpp/daal/src/services/service_topo.cpp
  cpp/daal/src/services/service_topo.h
Labels: bug

#3284 [CI] swap uxl self-hosted runners to github hosted
  .github/workflows/ci.yml
Labels: infra

#3282 update version to 2025.8.0
  deploy/pkg-config/pkg-config.tpl
  dev/bazel/config/config.bzl
  docs/doxygen/doxygen_conf_cpp.txt
  docs/doxygen/doxygen_conf_cpp_examples.txt
  docs/doxygen/doxygen_conf_cpp_web.txt
  makefile.ver
Labels: infra

#3286 bazel http_archive removing
  MODULE.bazel
Labels: infra

#3283 Add error handling in cw_atomic to prevent erroneous method usage
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_atomic_dpc.cpp
Labels: bug

#3295 Fix: Nightly CI failures
  cpp/oneapi/dal/backend/primitives/reduction/reduction_rm_cw_wrapper_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_random_dpc.cpp
  cpp/oneapi/dal/backend/primitives/reduction/test/reduction_rm_uniform_dpc.cpp
Labels: bug

#3297 Resolution for failed anaconda channels
  .ci/env/apt.sh
Labels: bug

#3294 ENH: Improve numerical precision of logistic function
  cpp/daal/src/algorithms/objective_function/logistic_loss/logistic_loss_dense_default_batch_impl.i
  cpp/daal/src/externals/service_blas.h
  cpp/daal/src/externals/service_blas_declar_ref.h
  cpp/daal/src/externals/service_blas_mkl.h
  cpp/daal/src/externals/service_blas_ref.h
Labels: enhancement

#3302 FIX: Fix extra comma resulting in syntax error depending on defined macros
  cpp/oneapi/dal/detail/cpu.hpp
Labels: bug

#3307 FIX: Fix incorrect comparison for small rows threshold of linear regression
  cpp/daal/src/algorithms/linear_model/linear_model_train_normeq_update_impl.i
Labels: bug
