Repository uxlfoundation/oneDAL, pull requests merged in 2025-08, with the labels that each got.

#3310 fix: fix the perf for knn preidction
  cpp/oneapi/dal/algo/knn/backend/model_conversion.hpp
Labels: enhancement

#3309 Add LINKER options for oneDAL build
  INSTALL.md
  dev/make/compiler_definitions/clang.32e.mk
  dev/make/compiler_definitions/clang.ref.arm.mk
  dev/make/compiler_definitions/clang.ref.riscv64.mk
  dev/make/compiler_definitions/dpcpp.mk
  dev/make/compiler_definitions/gnu.32e.mk
  dev/make/compiler_definitions/gnu.mk
  dev/make/compiler_definitions/gnu.ref.arm.mk
  dev/make/compiler_definitions/icc.mkl.32e.mk
  dev/make/compiler_definitions/icx.mkl.32e.mk
  dev/make/function_definitions/32e.mk
Labels: infra

#3311 [maint] remove descriptor_base_t alias
  cpp/oneapi/dal/algo/basic_statistics/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/basic_statistics/detail/finalize_compute_ops.hpp
  cpp/oneapi/dal/algo/basic_statistics/detail/partial_compute_ops.hpp
  cpp/oneapi/dal/algo/connected_components/detail/vertex_partitioning_ops.hpp
  cpp/oneapi/dal/algo/correlation_distance/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/cosine_distance/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/covariance/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/covariance/detail/finalize_compute_ops.hpp
  cpp/oneapi/dal/algo/covariance/detail/partial_compute_ops.hpp
  cpp/oneapi/dal/algo/dbscan/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/decision_forest/detail/train_ops.hpp
  cpp/oneapi/dal/algo/finiteness_checker/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/jaccard/detail/vertex_similarity_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/kmeans/detail/train_ops.hpp
  cpp/oneapi/dal/algo/kmeans_init/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/knn/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/knn/detail/train_ops.hpp
  cpp/oneapi/dal/algo/linear_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/linear_regression/detail/finalize_train_ops.hpp
  cpp/oneapi/dal/algo/linear_regression/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/linear_regression/detail/partial_train_ops.hpp
  cpp/oneapi/dal/algo/linear_regression/detail/train_ops.hpp
  cpp/oneapi/dal/algo/logistic_regression/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/logistic_regression/detail/train_ops.hpp
  cpp/oneapi/dal/algo/louvain/detail/vertex_partitioning_ops.hpp
  cpp/oneapi/dal/algo/objective_function/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/pca/detail/finalize_train_ops.hpp
  cpp/oneapi/dal/algo/pca/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/pca/detail/partial_train_ops.hpp
  cpp/oneapi/dal/algo/pca/detail/train_ops.hpp
  cpp/oneapi/dal/algo/polynomial_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/rbf_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/shortest_paths/detail/traverse_ops.hpp
  cpp/oneapi/dal/algo/sigmoid_kernel/detail/compute_ops.hpp
  cpp/oneapi/dal/algo/subgraph_isomorphism/detail/graph_matching_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/infer_ops.hpp
  cpp/oneapi/dal/algo/svm/detail/train_ops.hpp
  cpp/oneapi/dal/algo/triangle_counting/detail/vertex_ranking_ops.hpp
Labels: enhancement

#3312 FIX: Check status code after every call
  cpp/daal/src/algorithms/k_nearest_neighbors/bf_knn_classification_train_container.h
Labels: bug

#3328 Fix catch2 posix signals handling
  MODULE.bazel
  cpp/oneapi/dal/test/engine/catch.hpp
  dev/bazel/deps/catch2.BUILD
Labels: dependencies

#3334 Update PR template
  .github/pull_request_template.md
Labels: enhancement
